(()=>{
const STATE='compendiumAbilityStatesV1';
function state(){try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return{}}}
function enabled(id){const s=state()[id];return s?.unlocked===true&&s?.enabled===true}
function css(){if(document.getElementById('abilityEffectsV80'))return;const s=document.createElement('style');s.id='abilityEffectsV80';s.textContent=`
.swallow-gentle-slide{position:fixed;z-index:2147483647;left:-56px;top:24vh;width:34px;height:18px;pointer-events:none;opacity:0}.swallow-gentle-slide::before,.swallow-gentle-slide::after{content:"";position:absolute;top:7px;width:19px;height:2px;background:currentColor;border-radius:99px}.swallow-gentle-slide::before{left:0;transform:rotate(22deg)}.swallow-gentle-slide::after{right:0;transform:rotate(-22deg)}.swallow-gentle-slide.fly{animation:swallowGentleSlide 1.2s ease-in-out forwards}@keyframes swallowGentleSlide{0%{left:-56px;opacity:0;top:25vh}12%{opacity:.72}50%{top:22vh}88%{opacity:.68}100%{left:calc(100vw + 56px);opacity:0;top:24vh}}
html[data-ability-magpie="on"] .bird-tile .tile-photo{filter:grayscale(.8) contrast(1.05)}html[data-ability-magpie="on"] .bird-tile:hover .tile-photo{filter:grayscale(.35) contrast(1.05)}
html[data-ability-kingfisher="on"] .bird-tile.kingfisher-accent{box-shadow:inset 0 0 0 2px rgba(65,155,255,.8),0 0 18px rgba(65,155,255,.16)}
html[data-ability-pigeon="on"] #detailDialog[data-repeat-sighting="yes"] #detailMeta::after{content:"  🕊️"}
html[data-ability-ripple="on"] .bird-tile:hover{transform:translateY(-2px) rotate(.15deg);transition:transform .18s ease}
html[data-ability-rarity-glow="on"] .rarity-dot{filter:drop-shadow(0 0 5px currentColor)}
html[data-ability-prism="on"] .points-counter{background:linear-gradient(110deg,var(--panel),color-mix(in srgb,#9b59ff 16%,var(--panel)),color-mix(in srgb,#36c66b 13%,var(--panel)))}
html[data-ability-spectrum="on"] .bird-tile{outline:1px solid color-mix(in srgb,#a75cff 45%,transparent)}
@media(prefers-reduced-motion:reduce){.swallow-gentle-slide{display:none!important}}
`;document.head.appendChild(s)}
function playSwallow(){if(!enabled('swallow'))return;const d=document.getElementById('detailDialog');if(!d?.open)return;document.querySelectorAll('.swallow-gentle-slide').forEach(x=>x.remove());const el=document.createElement('div');el.className='swallow-gentle-slide';el.setAttribute('aria-hidden','true');document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('fly'));setTimeout(()=>el.remove(),1350)}
function feather(){const img=document.querySelector('.brand-bird');if(!img)return;let f=document.getElementById('abilityFeatherLogo');if(enabled('feather-logo')){img.style.display='none';if(!f){f=document.createElement('span');f.id='abilityFeatherLogo';f.textContent='🪶';f.style.fontSize='30px';img.after(f)}}else{img.style.display='';f?.remove()}}
function tileAccents(){document.querySelectorAll('.bird-tile').forEach(t=>{const n=(t.querySelector('.tile-name')?.textContent||'').toLowerCase();t.classList.toggle('kingfisher-accent',/kingfisher|kookaburra/.test(n))});const meta=document.getElementById('detailMeta'),dialog=document.getElementById('detailDialog');if(meta&&dialog){const m=meta.textContent.match(/(\d+)\s+sightings?/i);dialog.dataset.repeatSighting=Number(m?.[1]||0)>1?'yes':'no'}}
const malteseText=new Map([
['The Compendium','Il-Kompendju'],['Compendium','Kompendju'],['Families','Familji'],['Achievements','Kisbiet'],['Trophies','Trofej'],['Items','Oġġetti'],['Add species','Żid speċi'],['Add bird','Żid għasfur'],['Save','Issejvja'],['Cancel','Ikkanċella'],['Edit sighting','Editja osservazzjoni'],['Add sighting','Żid osservazzjoni'],['Sightings','Osservazzjonijiet'],['Common name','Isem komuni'],['Scientific name','Isem xjentifiku'],['General notes','Noti ġenerali'],['First sighting','L-ewwel osservazzjoni'],['Date','Data'],['Location','Post'],['Sighting notes','Noti tal-osservazzjoni'],['Country','Pajjiż'],['Class','Klassi'],['Use GPS','Uża GPS'],['Look up species','Fittex l-ispeċi'],['Delete','Ħassar'],['Edit','Editja'],['All','Kollha'],['Common','Komuni'],['Uncommon','Mhux komuni'],['Epic','Epiku'],['Mythical','Mitiku'],['Legendary','Leġġendarju'],['Sync','Sinkronizza'],['Synced','Sinkronizzat']
]);
function translatedText(original){if(malteseText.has(original))return malteseText.get(original);const m=original.match(/^(\d+) species discovered$/);if(m)return`${m[1]} speċi misjuba`;return original}
function restoreMaltese(){document.querySelectorAll('[data-comp-mt-original]').forEach(el=>{el.textContent=el.dataset.compMtOriginal;delete el.dataset.compMtOriginal});document.querySelectorAll('[data-comp-mt-placeholder]').forEach(el=>{el.placeholder=el.dataset.compMtPlaceholder;delete el.dataset.compMtPlaceholder})}
function applyMaltese(){restoreMaltese();if(!enabled('maltese'))return;document.querySelectorAll('button,h1,h2,h3,label>span,legend,.comp-nav-btn,.ach-tab,.filter-chip,#summaryText').forEach(el=>{if(el.closest('.scientific'))return;const old=el.textContent.trim(),tr=translatedText(old);if(tr!==old){el.dataset.compMtOriginal=el.textContent;el.textContent=tr}});const search=document.getElementById('searchInput');if(search){search.dataset.compMtPlaceholder=search.placeholder;search.placeholder='Fittex bl-isem komuni…'}const title=document.querySelector('.brand-title');if(title&&!title.dataset.compMtOriginal){title.dataset.compMtOriginal=title.textContent;title.textContent='Il-Kompendju'}}
function walkText(fn){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){const p=n.parentElement;if(!p||p.closest('script,style,textarea,input,select,option,.scientific,[data-no-ability-eye]'))continue;fn(n)}}
function restoreEyes(){walkText(n=>{if(n.__compEyeOriginal!==undefined){n.nodeValue=n.__compEyeOriginal;delete n.__compEyeOriginal}})}
function applyEyes(){restoreEyes();if(!enabled('eyes'))return;walkText(n=>{if(!/[oO]/.test(n.nodeValue||''))return;n.__compEyeOriginal=n.nodeValue;n.nodeValue=n.nodeValue.replace(/O/g,'👁️').replace(/o/g,'👁️')})}
function refresh(){const ids=['magpie','kingfisher','pigeon','ripple','rarity-glow','prism','spectrum'];for(const id of ids)document.documentElement.dataset['ability'+id.replace(/(^|-)(.)/g,(_,a,b)=>b.toUpperCase())]=enabled(id)?'on':'off';feather();restoreEyes();restoreMaltese();applyMaltese();applyEyes();tileAccents()}
function schedule(){setTimeout(refresh,80);setTimeout(refresh,300)}
function init(){css();refresh();document.addEventListener('click',e=>{if(e.target.closest?.('.bird-tile'))setTimeout(playSwallow,70);schedule()});addEventListener('achievement-abilities-changed',schedule);addEventListener('bird-local-change',schedule);addEventListener('open-achievements',schedule);addEventListener('focus',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();