(()=>{
const POINTS={common:1,uncommon:5,epic:20,mythical:50,legendary:150};
const RARITY={
 common:{label:'Common',color:'#ff8a1f',targets:[25,50,100,500]},
 uncommon:{label:'Uncommon',color:'#36c66b',targets:[15,35,75,150]},
 epic:{label:'Epic',color:'#3f8cff',targets:[10,25,50,100]},
 mythical:{label:'Mythical',color:'#a75cff',targets:[5,15,30,50]},
 legendary:{label:'Legendary',color:'#f4c542',targets:[3,10,20,50]}
};
const DB='birdCompendiumDB',STORE='birds';
let view=null,db=null,activeSubtab='achievements';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
function injectStyles(){if(document.getElementById('achievementStyles'))return;const s=document.createElement('style');s.id='achievementStyles';s.textContent=`
#achievementsView{display:none}.ach-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin:8px 0 12px;flex-wrap:wrap}.ach-head h2{margin:0;font-size:28px}.ach-head p{margin:4px 0 0}.ach-summary{display:flex;gap:9px;flex-wrap:wrap}.ach-pill{padding:8px 11px;border-radius:999px;background:var(--panel);border:1px solid var(--line);font-size:12px;font-weight:800}.ach-tabs{display:flex;gap:8px;margin:4px 0 18px;border-bottom:1px solid var(--line);padding-bottom:8px}.ach-tab{border:0;background:transparent;color:var(--muted);padding:9px 13px;border-radius:12px;font-weight:900}.ach-tab.active{background:var(--panel2);color:var(--text)}.ach-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:12px}.ach-card{border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:15px;position:relative;overflow:hidden}.ach-card.done{border-color:color-mix(in srgb,var(--text) 30%,var(--line));background:color-mix(in srgb,var(--panel2) 88%,var(--panel))}.ach-icon{font-size:28px;line-height:1;margin-bottom:9px}.ach-name{font-size:16px;font-weight:900}.ach-desc{color:var(--muted);font-size:12px;margin:4px 0 11px;min-height:31px}.ach-progress-row{display:flex;justify-content:space-between;gap:10px;font-size:11px;color:var(--muted);margin-bottom:6px}.ach-bar{height:8px;border-radius:999px;background:var(--bg);overflow:hidden;border:1px solid var(--line)}.ach-bar-fill{height:100%;background:var(--text);border-radius:999px}.ach-card.done .ach-bar-fill{width:100%!important}.ach-done-badge{position:absolute;top:12px;right:12px;font-size:11px;font-weight:900;padding:5px 8px;border-radius:999px;background:var(--text);color:var(--bg)}.ach-section-title{font-size:14px;font-weight:900;margin:24px 0 10px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.ach-note{margin-top:18px;color:var(--muted);font-size:11px}
.trophy-tier{margin:0 0 24px}.trophy-tier-head{display:flex;align-items:center;gap:9px;margin-bottom:10px}.trophy-dot{width:12px;height:12px;border-radius:50%}.trophy-tier-name{font-size:17px;font-weight:950}.trophy-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.trophy-card{border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:14px;text-align:center;position:relative;overflow:hidden}.trophy-card.locked{opacity:.58}.trophy-card.unlocked{box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--trophy-color) 55%,transparent)}.trophy-art{height:88px;display:flex;align-items:center;justify-content:center;position:relative;margin-bottom:7px}.trophy-cup{font-size:58px;filter:grayscale(1) brightness(.7);line-height:1}.trophy-card.unlocked .trophy-cup{filter:none}.trophy-stars{position:absolute;bottom:1px;left:50%;transform:translateX(-50%);white-space:nowrap;font-size:18px;letter-spacing:1px;color:var(--trophy-color);text-shadow:0 1px 2px rgba(0,0,0,.5)}.legend-trophy .trophy-art{height:88px}.legend-emblem{width:72px;height:72px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 35% 30%,color-mix(in srgb,var(--trophy-color) 90%,white),var(--trophy-color) 48%,color-mix(in srgb,var(--trophy-color) 45%,black));border:3px solid color-mix(in srgb,var(--trophy-color) 70%,white);box-shadow:0 0 22px color-mix(in srgb,var(--trophy-color) 35%,transparent);font-size:34px}.locked .legend-emblem{filter:grayscale(1);opacity:.55;box-shadow:none}.trophy-name{font-weight:950;font-size:14px}.trophy-target{color:var(--muted);font-size:11px;margin-top:3px}.trophy-progress{font-size:11px;margin-top:8px;font-weight:800}.trophy-unlocked{position:absolute;top:9px;right:9px;font-size:10px;font-weight:950;padding:4px 7px;border-radius:999px;background:var(--trophy-color);color:#101214}
.item-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}.item-card{border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:15px;display:flex;gap:13px;align-items:flex-start;position:relative}.item-card.locked{opacity:.52}.item-icon{width:54px;height:54px;border-radius:14px;background:var(--panel2);display:flex;align-items:center;justify-content:center;font-size:30px;flex:0 0 auto}.item-card.obtained .item-icon{box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--text) 22%,transparent)}.item-info{min-width:0}.item-name{font-weight:950}.item-desc{color:var(--muted);font-size:12px;margin-top:3px;line-height:1.35}.item-req{font-size:11px;margin-top:8px;font-weight:800}.item-status{position:absolute;top:9px;right:9px;font-size:10px;font-weight:950;padding:4px 7px;border-radius:999px;background:var(--text);color:var(--bg)}
@media(max-width:700px){.ach-grid{grid-template-columns:1fr 1fr}.ach-card{padding:12px}.ach-desc{min-height:44px}.ach-head h2{font-size:24px}.trophy-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:470px){.ach-grid{grid-template-columns:1fr}.item-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function openDB(){if(db)return db;db=await new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return db}
async function getBirds(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function stats(birds){const rarity={common:0,uncommon:0,epic:0,mythical:0,legendary:0};let photos=0,sightings=0;const locations=new Set(),countries=new Set();for(const b of birds){rarity[b.rarity]=(rarity[b.rarity]||0)+1;for(const s of b.sightings||[]){sightings++;for(const p of s.photos||[])photos++;if(s.location)locations.add(s.location.trim().toLowerCase())}if(b.country)countries.add(b.country.trim().toLowerCase())}const points=birds.reduce((n,b)=>n+(POINTS[b.rarity]||0),0);return{species:birds.length,points,rarity,photos,sightings,locations:locations.size,countries:countries.size,multi:birds.filter(b=>(b.sightings||[]).length>=2).length,withNotes:birds.filter(b=>String(b.notes||'').trim()).length}}
function goals(st){return[
{group:'Getting started',icon:'🪶',name:'First Feather',desc:'Add your first species to The Compendium.',value:st.species,target:1},{group:'Getting started',icon:'📸',name:'Proof of Life',desc:'Store at least one bird photo.',value:st.photos,target:1},{group:'Getting started',icon:'⭐',name:'On the Board',desc:'Reach 5 total points.',value:st.points,target:5},{group:'Getting started',icon:'🗺️',name:'Field Note',desc:'Record your first named sighting location.',value:st.locations,target:1},
{group:'Collection',icon:'🐦',name:'Small Flock',desc:'Acquire 5 species.',value:st.species,target:5},{group:'Collection',icon:'🦜',name:'Proper Collection',desc:'Acquire 10 species.',value:st.species,target:10},{group:'Collection',icon:'🦅',name:'Serious Birder',desc:'Acquire 25 species.',value:st.species,target:25},{group:'Collection',icon:'🏛️',name:'Natural History Wing',desc:'Acquire 50 species.',value:st.species,target:50},{group:'Collection',icon:'👑',name:'The Catalogue',desc:'Acquire 100 species.',value:st.species,target:100},
{group:'Rarity',icon:'🟢',name:'Something Uncommon',desc:'Acquire an Uncommon species.',value:st.rarity.uncommon,target:1},{group:'Rarity',icon:'🔵',name:'Epic Find',desc:'Acquire an Epic species.',value:st.rarity.epic,target:1},{group:'Rarity',icon:'🟣',name:'Myth Hunter',desc:'Acquire a Mythical species.',value:st.rarity.mythical,target:1},{group:'Rarity',icon:'🟡',name:'Legend Has It',desc:'Acquire a Legendary species.',value:st.rarity.legendary,target:1},{group:'Rarity',icon:'🌈',name:'Full Spectrum',desc:'Own at least one species from every rarity class.',value:['common','uncommon','epic','mythical','legendary'].filter(k=>st.rarity[k]>0).length,target:5},
{group:'Points',icon:'✨',name:'Pocket Change',desc:'Reach 25 points.',value:st.points,target:25},{group:'Points',icon:'💯',name:'Triple Digits',desc:'Reach 100 points.',value:st.points,target:100},{group:'Points',icon:'🏅',name:'Heavyweight',desc:'Reach 500 points.',value:st.points,target:500},{group:'Points',icon:'🏆',name:'Four Figures',desc:'Reach 1,000 points.',value:st.points,target:1000},
{group:'Fieldwork',icon:'📍',name:'Local Explorer',desc:'Record sightings at 5 different locations.',value:st.locations,target:5},{group:'Fieldwork',icon:'🧭',name:'Range Expansion',desc:'Record sightings at 15 different locations.',value:st.locations,target:15},{group:'Fieldwork',icon:'🌍',name:'Passport Stamps',desc:'Acquire birds from 3 different countries.',value:st.countries,target:3},{group:'Fieldwork',icon:'✈️',name:'International Birder',desc:'Acquire birds from 5 different countries.',value:st.countries,target:5},{group:'Fieldwork',icon:'🔁',name:'Seen You Before',desc:'Have 3 species with multiple sightings.',value:st.multi,target:3},{group:'Fieldwork',icon:'📚',name:'Field Journal',desc:'Add notes to 5 species.',value:st.withNotes,target:5},{group:'Fieldwork',icon:'🎞️',name:'Shutterbug',desc:'Store 25 sighting photos.',value:st.photos,target:25},{group:'Fieldwork',icon:'🗃️',name:'Archive Mode',desc:'Log 50 total sightings.',value:st.sightings,target:50}
]}
function items(st){return[
{name:'Worn Field Notebook',icon:'📓',desc:'Your first battered little record book.',value:st.species,target:1,req:'Acquire 1 species'},
{name:'Pocket Binoculars',icon:'🔭',desc:'Small, scratched, and suddenly indispensable.',value:st.species,target:5,req:'Acquire 5 species'},
{name:'Brass Compass',icon:'🧭',desc:'Points vaguely toward somewhere worth checking.',value:st.locations,target:3,req:'Log 3 locations'},
{name:'Lucky Feather',icon:'🪶',desc:'Probably does nothing. Obviously must be kept forever.',value:st.points,target:25,req:'Reach 25 points'},
{name:'Weathered Satchel',icon:'🎒',desc:'For carrying lenses, snacks, and increasingly unreasonable ambitions.',value:st.species,target:10,req:'Acquire 10 species'},
{name:'Film Canister',icon:'🎞️',desc:'A relic from the ancient age before everyone took 400 photos at once.',value:st.photos,target:10,req:'Store 10 photos'},
{name:'Ranger Map',icon:'🗺️',desc:'Marked with enough spots to start looking suspicious.',value:st.locations,target:10,req:'Log 10 locations'},
{name:'Stamped Passport',icon:'🛂',desc:'Proof the compendium has escaped the country.',value:st.countries,target:2,req:'Acquire birds in 2 countries'},
{name:'Silver Lens',icon:'🔘',desc:'A polished field lens awarded to persistent photographers.',value:st.photos,target:25,req:'Store 25 photos'},
{name:'Repeat-Sighting Token',icon:'🪙',desc:'For proving you can appreciate a bird twice instead of immediately chasing the next one.',value:st.multi,target:3,req:'3 species with repeat sightings'},
{name:'Naturalist’s Quill',icon:'✒️',desc:'Awarded for actually writing things down instead of trusting your memory.',value:st.withNotes,target:10,req:'Notes on 10 species'},
{name:'Prismatic Pin',icon:'🌈',desc:'A badge for collecting across every rarity tier.',value:['common','uncommon','epic','mythical','legendary'].filter(k=>st.rarity[k]>0).length,target:5,req:'Own every rarity tier'},
{name:'Gilded Scope',icon:'🔭',desc:'Ridiculously ornate. Completely unnecessary. Excellent.',value:st.points,target:500,req:'Reach 500 points'},
{name:'Archivist’s Key',icon:'🗝️',desc:'Supposedly opens the vault where all the blurry photos are hidden.',value:st.sightings,target:100,req:'Log 100 sightings'},
{name:'Crown of Feathers',icon:'👑',desc:'Endgame nonsense for someone who has clearly committed to the bit.',value:st.species,target:250,req:'Acquire 250 species'}
]}
function renderAchievements(st){const all=goals(st);let last='';for(const g of all){if(g.group!==last){last=g.group;const h=document.createElement('div');h.className='ach-section-title';h.textContent=last;view.appendChild(h);const grid=document.createElement('div');grid.className='ach-grid';view.appendChild(grid)}const grid=[...view.querySelectorAll('.ach-grid')].at(-1),pct=Math.max(0,Math.min(100,Math.round(g.value/g.target*100))),card=document.createElement('article');card.className='ach-card'+(g.value>=g.target?' done':'');card.innerHTML=`${g.value>=g.target?'<div class="ach-done-badge">Unlocked</div>':''}<div class="ach-icon">${g.icon}</div><div class="ach-name">${esc(g.name)}</div><div class="ach-desc">${esc(g.desc)}</div><div class="ach-progress-row"><span>${Math.min(g.value,g.target).toLocaleString()} / ${g.target.toLocaleString()}</span><span>${pct}%</span></div><div class="ach-bar"><div class="ach-bar-fill" style="width:${pct}%"></div></div>`;grid.appendChild(card)}}
function renderTrophies(st){for(const [key,r] of Object.entries(RARITY)){const section=document.createElement('section');section.className='trophy-tier';section.innerHTML=`<div class="trophy-tier-head"><span class="trophy-dot" style="background:${r.color}"></span><span class="trophy-tier-name">${r.label} Trophies</span><span class="muted small">${st.rarity[key]} species</span></div><div class="trophy-grid"></div>`;const grid=section.querySelector('.trophy-grid');r.targets.forEach((target,i)=>{const unlocked=st.rarity[key]>=target,legend=i===3,stars='★'.repeat(i+1);const card=document.createElement('article');card.className=`trophy-card ${unlocked?'unlocked':'locked'} ${legend?'legend-trophy':''}`;card.style.setProperty('--trophy-color',r.color);card.innerHTML=`${unlocked?'<div class="trophy-unlocked">Unlocked</div>':''}<div class="trophy-art">${legend?`<div class="legend-emblem">♛</div>`:`<div class="trophy-cup">🏆</div><div class="trophy-stars">${stars}</div>`}</div><div class="trophy-name">${legend?`${r.label} Legend Trophy`:`${i+1}-Star ${r.label} Trophy`}</div><div class="trophy-target">${target} ${r.label.toLowerCase()} species</div><div class="trophy-progress">${Math.min(st.rarity[key],target)} / ${target}</div>`;grid.appendChild(card)});view.appendChild(section)}}
function renderItems(st){const intro=document.createElement('div');intro.className='ach-note';intro.style.margin='0 0 14px';intro.textContent='Items are collectible field-game rewards. They do not change rarity or points; they are just trophies with more personality.';view.appendChild(intro);const grid=document.createElement('div');grid.className='item-grid';for(const it of items(st)){const got=it.value>=it.target,card=document.createElement('article');card.className=`item-card ${got?'obtained':'locked'}`;card.innerHTML=`${got?'<div class="item-status">Obtained</div>':''}<div class="item-icon">${it.icon}</div><div class="item-info"><div class="item-name">${esc(it.name)}</div><div class="item-desc">${esc(it.desc)}</div><div class="item-req">${esc(it.req)} • ${Math.min(it.value,it.target)} / ${it.target}</div></div>`;grid.appendChild(card)}view.appendChild(grid)}
function hideMain(){for(const sel of ['.toolbar','#rarityFilters','#birdGrid','#emptyState','#mobileAddDock','#familiesView']){const el=document.querySelector(sel);if(el)el.style.display='none'}const add=document.getElementById('addBirdBtn');if(add)add.style.display='none';const sum=document.getElementById('summaryText');if(sum)sum.style.display='none';document.querySelectorAll('.comp-nav-btn').forEach(b=>b.classList.remove('active'))}
async function render(){const birds=await getBirds(),st=stats(birds),all=goals(st),done=all.filter(g=>g.value>=g.target).length,trophyCount=Object.entries(RARITY).reduce((n,[k,r])=>n+r.targets.filter(t=>st.rarity[k]>=t).length,0),itemCount=items(st).filter(i=>i.value>=i.target).length;view.innerHTML=`<div class="ach-head"><div><h2>Achievements</h2><p class="muted">Milestones, trophy shelves, and collectible field loot.</p></div><div class="ach-summary"><span class="ach-pill">${done}/${all.length} achievements</span><span class="ach-pill">🏆 ${trophyCount}/20 trophies</span><span class="ach-pill">🎒 ${itemCount}/${items(st).length} items</span><span class="ach-pill">★ ${st.points.toLocaleString()} pts</span></div></div><div class="ach-tabs"><button class="ach-tab ${activeSubtab==='achievements'?'active':''}" data-ach-sub="achievements">Achievements</button><button class="ach-tab ${activeSubtab==='trophies'?'active':''}" data-ach-sub="trophies">Trophies</button><button class="ach-tab ${activeSubtab==='items'?'active':''}" data-ach-sub="items">Items</button></div>`;view.querySelectorAll('[data-ach-sub]').forEach(b=>b.onclick=()=>{activeSubtab=b.dataset.achSub;render()});if(activeSubtab==='trophies')renderTrophies(st);else if(activeSubtab==='items')renderItems(st);else renderAchievements(st);const note=document.createElement('div');note.className='ach-note';note.textContent='Everything updates automatically from the species and sightings already stored in your Compendium.';view.appendChild(note)}
async function show(){hideMain();view.style.display='block';document.querySelector('[data-comp-tab="achievements"]')?.classList.add('active');await render();window.scrollTo({top:0,behavior:'smooth'})}
function installNav(){let nav=document.querySelector('.comp-nav');if(!nav){const top=document.querySelector('.topbar');if(!top)return;nav=document.createElement('nav');nav.className='comp-nav';top.insertAdjacentElement('afterend',nav)}if(!nav.querySelector('[data-comp-tab="achievements"]')){const b=document.createElement('button');b.className='comp-nav-btn';b.dataset.compTab='achievements';b.textContent='Achievements';b.onclick=show;nav.appendChild(b)}}
function init(){injectStyles();view=document.createElement('section');view.id='achievementsView';document.getElementById('app')?.appendChild(view);setTimeout(installNav,100);setTimeout(installNav,800);window.addEventListener('open-achievements',show);window.addEventListener('bird-local-change',()=>{if(view?.style.display==='block')setTimeout(render,150)});document.addEventListener('click',e=>{if(e.target.closest?.('[data-comp-tab="compendium"],[data-comp-tab="families"]')){if(view)view.style.display='none';document.querySelector('[data-comp-tab="achievements"]')?.classList.remove('active')}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();