(()=>{
const DB='birdCompendiumDB',STORE='birds',BONUS_KEY='compendiumAchievementBonusV1',STATE='compendiumAbilityStatesV1',UNLOCK='compendiumUnlockedAbilitiesV1';
const POINT_REWARDS={
'Proof of Life':1,'Field Note':1,'Small Flock':2,'Proper Collection':3,'Serious Birder':4,'Natural History Wing':10,'The Catalogue':50,'Wizard':100,
'Epic Find':10,'Myth Hunter':25,'Legend Has It':50,'Pocket Change':5,'Triple Digits':20,'Heavyweight':30,'Four Figures':99,
'Range Expansion':7,'International Birder':36,'Shutterbug':4,'Archive Mode':13
};
const ABILITY_REWARDS={
'First Feather':['feather-logo','Changes the icon next to The Compendium logo to a feather.'],
'On the Board':['theme-light','Unlocks the Theme selector and the Light theme.'],
'Something Uncommon':['font-garamond','Unlocks the Font selector and Garamond.'],
'Full Spectrum':['spectrum','Adds a rarity-spectrum accent around acquired bird tiles.'],
'Passport Stamps':['maltese','Translates the app interface, including The Compendium logo title, into Maltese.'],
'Field Journal':['theme-field','Unlocks the Parchment and Khaki themes.'],
'Seen You Before':['eyes','Turns every O in the app interface into an eye emoji while enabled.'],
'Local Explorer':['font-local','Unlocks Georgia and Typewriter fonts.']
};
let db=null,running=false,pending=false,timer=null;
const norm=s=>String(s||'').trim().toLowerCase().replace(/[’']/g,"'").replace(/[^a-z0-9' ]+/g,' ').replace(/\s+/g,' ').trim();
async function birds(){if(!db)db=await new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
function match(b,common=[],scientific=[]){const c=norm(b.commonName),s=norm(b.scientificName);return common.some(x=>c===norm(x))||scientific.some(x=>s===norm(x))}
function hasSpecies(b,common,scientific=[]){return b.some(x=>match(x,Array.isArray(common)?common:[common],Array.isArray(scientific)?scientific:[scientific]))}
function findSpecies(b,common,scientific=[]){return b.find(x=>match(x,Array.isArray(common)?common:[common],Array.isArray(scientific)?scientific:[scientific]))}
function countNames(b,words){return b.filter(x=>words.some(w=>norm(x.commonName).includes(norm(w)))).length}
function extraChallenges(b){return[
{name:'Sydney Starter Pack',icon:'🦜',desc:'Find Rainbow Lorikeet, Sulphur-crested Cockatoo and Australian Magpie.',type:'points',reward:8,value:[hasSpecies(b,['Rainbow Lorikeet'],['Trichoglossus moluccanus']),hasSpecies(b,['Sulphur-crested Cockatoo'],['Cacatua galerita']),hasSpecies(b,['Australian Magpie'],['Gymnorhina tibicen'])].filter(Boolean).length,target:3},
{name:'Harbour Patrol',icon:'🌊',desc:'Find Silver Gull, Australian Pelican and a Pied Cormorant.',type:'ability',reward:['ripple','Adds a subtle ripple/hover flourish to acquired bird tiles.'],value:[hasSpecies(b,['Silver Gull'],['Chroicocephalus novaehollandiae']),hasSpecies(b,['Australian Pelican'],['Pelecanus conspicillatus']),hasSpecies(b,['Pied Cormorant','Great Cormorant'],['Phalacrocorax varius'])].filter(Boolean).length,target:3},
{name:'After Dark',icon:'🦉',desc:'Find a Tawny Frogmouth.',type:'points',reward:12,value:hasSpecies(b,['Tawny Frogmouth'],['Podargus strigoides'])?1:0,target:1},
{name:'Tiny Royalty',icon:'🧚',desc:'Find a Superb Fairywren.',type:'ability',reward:['rarity-glow','Adds a subtle glow to rarity dots.'],value:hasSpecies(b,['Superb Fairywren','Superb Fairy-wren'],['Malurus cyaneus'])?1:0,target:1},
{name:'Indian Invasion',icon:'🐦',desc:'Find a Common Myna (Indian Myna).',type:'points',reward:3,value:hasSpecies(b,['Common Myna','Indian Myna','Indian Miner'],['Acridotheres tristis'])?1:0,target:1},
{name:'Rock Around the Clock',icon:'🕊️',desc:'Record 15 Rock Dove / Rock Pigeon sightings.',type:'ability',reward:['pigeon','Adds a tiny pigeon stamp beside repeat-sighting information.'],value:(findSpecies(b,['Rock Dove','Rock Pigeon','Feral Pigeon'],['Columba livia'])?.sightings||[]).length,target:15},
{name:'Bin Chicken Initiation',icon:'🗑️',desc:'Find an Australian White Ibis.',type:'points',reward:2,value:hasSpecies(b,['Australian White Ibis','White Ibis','Australian Ibis'],['Threskiornis molucca'])?1:0,target:1},
{name:'Masked Menace',icon:'🎭',desc:'Find a Masked Lapwing.',type:'points',reward:3,value:hasSpecies(b,['Masked Lapwing','Spur-winged Plover'],['Vanellus miles'])?1:0,target:1},
{name:'Welcome Swallow',icon:'👋',desc:'Find a Welcome Swallow.',type:'ability',reward:['swallow','Adds a gentle bird-shaped side-slide flourish when opening an acquired bird card.'],value:hasSpecies(b,['Welcome Swallow'],['Hirundo neoxena'])?1:0,target:1},
{name:'Pelican Brief',icon:'📄',desc:'Find an Australian Pelican.',type:'points',reward:4,value:hasSpecies(b,['Australian Pelican'],['Pelecanus conspicillatus'])?1:0,target:1},
{name:'Lorikeet Tax',icon:'🌈',desc:'Record 10 Rainbow Lorikeet sightings.',type:'points',reward:10,value:(findSpecies(b,['Rainbow Lorikeet'],['Trichoglossus moluccanus'])?.sightings||[]).length,target:10},
{name:'Magpie Diplomacy',icon:'⚫',desc:'Record 10 Australian Magpie sightings.',type:'ability',reward:['magpie','Adds a monochrome treatment to acquired tile photography.'],value:(findSpecies(b,['Australian Magpie'],['Gymnorhina tibicen'])?.sightings||[]).length,target:10},
{name:'Cormorant Committee',icon:'🌊',desc:'Collect 3 different cormorant species.',type:'points',reward:14,value:countNames(b,['cormorant']),target:3},
{name:'Honeyeater Union',icon:'🍯',desc:'Collect 5 honeyeaters, miners or wattlebirds.',type:'points',reward:15,value:countNames(b,['honeyeater','miner','wattlebird']),target:5},
{name:'Duck Department',icon:'🦆',desc:'Collect 6 duck-family species.',type:'points',reward:18,value:countNames(b,['duck','teal','shoveler','shelduck','hardhead','mallard']),target:6},
{name:'Kingfisher Cabinet',icon:'🐟',desc:'Collect 3 kingfishers or kookaburras.',type:'ability',reward:['kingfisher','Adds a blue family accent to kingfisher and kookaburra cards.'],value:countNames(b,['kingfisher','kookaburra']),target:3},
{name:'Raptor Audit',icon:'🦅',desc:'Collect 4 raptor species.',type:'points',reward:30,value:countNames(b,['eagle','kite','hawk','falcon','goshawk','harrier','osprey']),target:4},
{name:'Parrot Problem',icon:'🦜',desc:'Collect 8 parrots, lorikeets, rosellas, corellas, galahs or cockatoos.',type:'ability',reward:['prism','Gives the points badge a subtle prismatic sheen.'],value:countNames(b,['parrot','lorikeet','cockatoo','rosella','corella','galah']),target:8}
]}
function readState(){try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return{}}}
function writeState(s){localStorage.setItem(STATE,JSON.stringify(s));localStorage.setItem(UNLOCK,JSON.stringify(Object.entries(s).filter(([,v])=>v?.unlocked).map(([id])=>id)));dispatchEvent(new Event('achievement-abilities-changed'))}
function ensureCss(){if(document.getElementById('achievementRewardStylesV82'))return;const s=document.createElement('style');s.id='achievementRewardStylesV82';s.textContent=`.reward-ability-icon{border:2px solid var(--muted)!important;border-radius:13px;padding:6px;display:inline-flex!important}.reward-points{font-size:10px;font-weight:900;color:var(--muted);margin-left:7px}.reward-ability-preview{font-size:11px;color:var(--muted);margin:8px 0;line-height:1.35}.reward-toggle{margin-top:8px;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:9px;padding:7px 10px;font-weight:850}.reward-toggle[disabled]{opacity:.42;cursor:not-allowed}.ach-icon-row{display:flex;align-items:center;gap:5px;margin-bottom:8px}`;document.head.appendChild(s)}
function setAbility(state,id,done){if(done){if(!state[id])state[id]={unlocked:true,enabled:false};else state[id].unlocked=true}}
function addToggle(card,id,state,done){const old=card.querySelector('.reward-toggle');old?.remove();if(!done)return;const bt=document.createElement('button');bt.type='button';bt.className='reward-toggle';bt.textContent=state[id]?.enabled?'Enabled':'Disabled';bt.setAttribute('aria-pressed',state[id]?.enabled?'true':'false');bt.onclick=e=>{e.preventDefault();e.stopPropagation();const s=readState();if(!s[id]?.unlocked)return;s[id].enabled=!s[id].enabled;writeState(s);schedule()};card.appendChild(bt)}
async function decorate(){if(running){pending=true;return}running=true;try{const v=document.getElementById('achievementsView');if(!v||getComputedStyle(v).display==='none')return;const b=await birds();let state=readState(),bonus=0;
for(const c of v.querySelectorAll('.ach-card')){if(c.closest('.species-achievements'))continue;const name=c.querySelector('.ach-name')?.textContent?.trim(),done=c.classList.contains('done'),icon=c.querySelector('.ach-icon');if(!name||!icon)continue;c.querySelectorAll('.reward-points,.reward-ability-preview,.reward-toggle').forEach(x=>x.remove());icon.classList.remove('reward-ability-icon');if(POINT_REWARDS[name]!=null){icon.insertAdjacentHTML('afterend',`<small class="reward-points">+${POINT_REWARDS[name]} pts</small>`);if(done)bonus+=POINT_REWARDS[name]}if(ABILITY_REWARDS[name]){const[id,desc]=ABILITY_REWARDS[name];icon.classList.add('reward-ability-icon');c.insertAdjacentHTML('beforeend',`<div class="reward-ability-preview"><b>Ability:</b> ${desc}</div>`);setAbility(state,id,done);addToggle(c,id,state,done)}}
const old=v.querySelector('.species-achievements');old?.remove();const sec=document.createElement('section');sec.className='species-achievements';sec.innerHTML='<div class="ach-section-title">Sydney & species challenges</div><div class="ach-grid"></div>';const grid=sec.querySelector('.ach-grid');for(const g of extraChallenges(b)){const done=g.value>=g.target,pct=Math.max(0,Math.min(100,Math.round((g.value/g.target)*100))),card=document.createElement('article');card.className='ach-card'+(done?' done':'');let label='';if(g.type==='points'){label=`+${g.reward} pts`;if(done)bonus+=g.reward}else{const[id]=g.reward;label='Ability';setAbility(state,id,done)}card.innerHTML=`${done?'<div class="ach-done-badge">Unlocked</div>':''}<div class="ach-icon-row"><span class="ach-icon ${g.type==='ability'?'reward-ability-icon':''}">${g.icon}</span><small class="reward-points">${label}</small></div><div class="ach-name">${g.name}</div><div class="ach-desc">${g.desc}</div>${g.type==='ability'?`<div class="reward-ability-preview"><b>Ability:</b> ${g.reward[1]}</div>`:''}<div class="ach-progress-row"><span>${Math.min(g.value,g.target)} / ${g.target}</span><span>${pct}%</span></div><div class="ach-bar"><div class="ach-bar-fill" style="width:${pct}%"></div></div>`;if(g.type==='ability')addToggle(card,g.reward[0],state,done);grid.appendChild(card)}v.appendChild(sec);
writeState(state);localStorage.setItem(BONUS_KEY,String(bonus));dispatchEvent(new CustomEvent('achievement-points',{detail:{bonus}}));dispatchEvent(new CustomEvent('achievements-refreshed',{detail:{birdCount:b.length,bonus}}));
}finally{running=false;if(pending){pending=false;setTimeout(decorate,80)}}}
function schedule(){clearTimeout(timer);timer=setTimeout(decorate,110)}
function init(){ensureCss();writeState(readState());addEventListener('open-achievements',()=>setTimeout(decorate,80));addEventListener('bird-local-change',schedule);addEventListener('focus',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule()});document.addEventListener('click',e=>{if(e.target.closest?.('[data-comp-tab="achievements"],[data-ach-sub="achievements"]'))setTimeout(decorate,90)});setTimeout(schedule,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();