(()=>{
const POINTS={common:1,uncommon:5,epic:20,mythical:50,legendary:150};
const DB='birdCompendiumDB',STORE='birds';
let view=null,db=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
function injectStyles(){if(document.getElementById('achievementStyles'))return;const s=document.createElement('style');s.id='achievementStyles';s.textContent=`
#achievementsView{display:none}.ach-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin:8px 0 18px;flex-wrap:wrap}.ach-head h2{margin:0;font-size:28px}.ach-head p{margin:4px 0 0}.ach-summary{display:flex;gap:9px;flex-wrap:wrap}.ach-pill{padding:8px 11px;border-radius:999px;background:var(--panel);border:1px solid var(--line);font-size:12px;font-weight:800}.ach-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(245px,1fr));gap:12px}.ach-card{border:1px solid var(--line);background:var(--panel);border-radius:18px;padding:15px;position:relative;overflow:hidden}.ach-card.done{border-color:color-mix(in srgb,var(--text) 30%,var(--line));background:color-mix(in srgb,var(--panel2) 88%,var(--panel))}.ach-icon{font-size:28px;line-height:1;margin-bottom:9px}.ach-name{font-size:16px;font-weight:900}.ach-desc{color:var(--muted);font-size:12px;margin:4px 0 11px;min-height:31px}.ach-progress-row{display:flex;justify-content:space-between;gap:10px;font-size:11px;color:var(--muted);margin-bottom:6px}.ach-bar{height:8px;border-radius:999px;background:var(--bg);overflow:hidden;border:1px solid var(--line)}.ach-bar-fill{height:100%;background:var(--text);border-radius:999px}.ach-card.done .ach-bar-fill{width:100%!important}.ach-done-badge{position:absolute;top:12px;right:12px;font-size:11px;font-weight:900;padding:5px 8px;border-radius:999px;background:var(--text);color:var(--bg)}.ach-section-title{font-size:14px;font-weight:900;margin:24px 0 10px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.ach-note{margin-top:18px;color:var(--muted);font-size:11px}
@media(max-width:700px){.ach-grid{grid-template-columns:1fr 1fr}.ach-card{padding:12px}.ach-desc{min-height:44px}.ach-head h2{font-size:24px}}@media(max-width:470px){.ach-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
async function openDB(){if(db)return db;db=await new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return db}
async function getBirds(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function stats(birds){const rarity={common:0,uncommon:0,epic:0,mythical:0,legendary:0};let photos=0,sightings=0;const locations=new Set(),countries=new Set();for(const b of birds){rarity[b.rarity] = (rarity[b.rarity]||0)+1;for(const s of b.sightings||[]){sightings++;for(const p of s.photos||[])photos++;if(s.location)locations.add(s.location.trim().toLowerCase())}if(b.country)countries.add(b.country.trim().toLowerCase())}const points=birds.reduce((n,b)=>n+(POINTS[b.rarity]||0),0);return{species:birds.length,points,rarity,photos,sightings,locations:locations.size,countries:countries.size,multi:birds.filter(b=>(b.sightings||[]).length>=2).length,withNotes:birds.filter(b=>String(b.notes||'').trim()).length}}
function goals(st){return[
{group:'Getting started',icon:'🪶',name:'First Feather',desc:'Add your first species to The Compendium.',value:st.species,target:1},
{group:'Getting started',icon:'📸',name:'Proof of Life',desc:'Store at least one bird photo.',value:st.photos,target:1},
{group:'Getting started',icon:'⭐',name:'On the Board',desc:'Reach 5 total points.',value:st.points,target:5},
{group:'Getting started',icon:'🗺️',name:'Field Note',desc:'Record your first named sighting location.',value:st.locations,target:1},
{group:'Collection',icon:'🐦',name:'Small Flock',desc:'Acquire 5 species.',value:st.species,target:5},
{group:'Collection',icon:'🦜',name:'Proper Collection',desc:'Acquire 10 species.',value:st.species,target:10},
{group:'Collection',icon:'🦅',name:'Serious Birder',desc:'Acquire 25 species.',value:st.species,target:25},
{group:'Collection',icon:'🏛️',name:'Natural History Wing',desc:'Acquire 50 species.',value:st.species,target:50},
{group:'Collection',icon:'👑',name:'The Catalogue',desc:'Acquire 100 species.',value:st.species,target:100},
{group:'Rarity',icon:'🟢',name:'Something Uncommon',desc:'Acquire an Uncommon species.',value:st.rarity.uncommon,target:1},
{group:'Rarity',icon:'🔵',name:'Epic Find',desc:'Acquire an Epic species.',value:st.rarity.epic,target:1},
{group:'Rarity',icon:'🟣',name:'Myth Hunter',desc:'Acquire a Mythical species.',value:st.rarity.mythical,target:1},
{group:'Rarity',icon:'🟡',name:'Legend Has It',desc:'Acquire a Legendary species.',value:st.rarity.legendary,target:1},
{group:'Rarity',icon:'🌈',name:'Full Spectrum',desc:'Own at least one species from every rarity class.',value:['common','uncommon','epic','mythical','legendary'].filter(k=>st.rarity[k]>0).length,target:5},
{group:'Points',icon:'✨',name:'Pocket Change',desc:'Reach 25 points.',value:st.points,target:25},
{group:'Points',icon:'💯',name:'Triple Digits',desc:'Reach 100 points.',value:st.points,target:100},
{group:'Points',icon:'🏅',name:'Heavyweight',desc:'Reach 500 points.',value:st.points,target:500},
{group:'Points',icon:'🏆',name:'Four Figures',desc:'Reach 1,000 points.',value:st.points,target:1000},
{group:'Fieldwork',icon:'📍',name:'Local Explorer',desc:'Record sightings at 5 different locations.',value:st.locations,target:5},
{group:'Fieldwork',icon:'🧭',name:'Range Expansion',desc:'Record sightings at 15 different locations.',value:st.locations,target:15},
{group:'Fieldwork',icon:'🌍',name:'Passport Stamps',desc:'Acquire birds from 3 different countries.',value:st.countries,target:3},
{group:'Fieldwork',icon:'✈️',name:'International Birder',desc:'Acquire birds from 5 different countries.',value:st.countries,target:5},
{group:'Fieldwork',icon:'🔁',name:'Seen You Before',desc:'Have 3 species with multiple sightings.',value:st.multi,target:3},
{group:'Fieldwork',icon:'📚',name:'Field Journal',desc:'Add notes to 5 species.',value:st.withNotes,target:5},
{group:'Fieldwork',icon:'🎞️',name:'Shutterbug',desc:'Store 25 sighting photos.',value:st.photos,target:25},
{group:'Fieldwork',icon:'🗃️',name:'Archive Mode',desc:'Log 50 total sightings.',value:st.sightings,target:50}
]}
function hideMain(){for(const sel of ['.toolbar','#rarityFilters','#birdGrid','#emptyState','#mobileAddDock','#familiesView']){const el=document.querySelector(sel);if(el)el.style.display='none'}const add=document.getElementById('addBirdBtn');if(add)add.style.display='none';const sum=document.getElementById('summaryText');if(sum)sum.style.display='none';document.querySelectorAll('.comp-nav-btn').forEach(b=>b.classList.remove('active'))}
function showCompendium(){if(view)view.style.display='none';window.dispatchEvent(new CustomEvent('achievements-closed'));const btn=document.querySelector('[data-comp-tab="compendium"]');if(btn)btn.click()}
async function render(){const birds=await getBirds(),st=stats(birds),all=goals(st),done=all.filter(g=>g.value>=g.target).length;view.innerHTML=`<div class="ach-head"><div><h2>Achievements</h2><p class="muted">Small wins, stupidly ambitious milestones, and an excuse to keep looking up.</p></div><div class="ach-summary"><span class="ach-pill">${done}/${all.length} unlocked</span><span class="ach-pill">★ ${st.points.toLocaleString()} pts</span></div></div>`;let last='';for(const g of all){if(g.group!==last){last=g.group;const h=document.createElement('div');h.className='ach-section-title';h.textContent=last;view.appendChild(h);const grid=document.createElement('div');grid.className='ach-grid';grid.dataset.group=last;view.appendChild(grid)}const grid=[...view.querySelectorAll('.ach-grid')].at(-1),pct=Math.max(0,Math.min(100,Math.round(g.value/g.target*100))),card=document.createElement('article');card.className='ach-card'+(g.value>=g.target?' done':'');card.innerHTML=`${g.value>=g.target?'<div class="ach-done-badge">Unlocked</div>':''}<div class="ach-icon">${g.icon}</div><div class="ach-name">${esc(g.name)}</div><div class="ach-desc">${esc(g.desc)}</div><div class="ach-progress-row"><span>${Math.min(g.value,g.target).toLocaleString()} / ${g.target.toLocaleString()}</span><span>${pct}%</span></div><div class="ach-bar"><div class="ach-bar-fill" style="width:${pct}%"></div></div>`;grid.appendChild(card)}const note=document.createElement('div');note.className='ach-note';note.textContent='Achievements are calculated from the birds and sightings already stored in your Compendium, so they update automatically as the collection grows.';view.appendChild(note)}
async function show(){hideMain();view.style.display='block';let b=document.querySelector('[data-comp-tab="achievements"]');if(b)b.classList.add('active');await render();window.scrollTo({top:0,behavior:'smooth'})}
function installNav(){let nav=document.querySelector('.comp-nav');if(!nav){const top=document.querySelector('.topbar');if(!top)return;nav=document.createElement('nav');nav.className='comp-nav';top.insertAdjacentElement('afterend',nav)}if(!nav.querySelector('[data-comp-tab="achievements"]')){const b=document.createElement('button');b.className='comp-nav-btn';b.dataset.compTab='achievements';b.textContent='Achievements';b.onclick=show;nav.appendChild(b)} }
function init(){injectStyles();view=document.createElement('section');view.id='achievementsView';document.getElementById('app')?.appendChild(view);setTimeout(installNav,100);setTimeout(installNav,800);window.addEventListener('open-achievements',show);window.addEventListener('bird-local-change',()=>{if(view?.style.display==='block')setTimeout(render,150)});document.addEventListener('click',e=>{if(e.target.closest?.('[data-comp-tab="compendium"],[data-comp-tab="families"]')){if(view)view.style.display='none';document.querySelector('[data-comp-tab="achievements"]')?.classList.remove('active')}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();