(()=>{
const DB='birdCompendiumDB',STORE='birds',BONUS_KEY='compendiumAchievementBonusV1',STATE='compendiumAbilityStatesV1';
const pointRewards={'Proof of Life':1,'Field Note':1,'Small Flock':2,'Proper Collection':3,'Serious Birder':4,'Natural History Wing':10,'The Catalogue':50,'Wizard':100,'Epic Find':10,'Myth Hunter':25,'Legend Has It':50,'Pocket Change':5,'Triple Digits':20,'Heavyweight':30,'Four Figures':99,'Range Expansion':7,'International Birder':36,'Shutterbug':4,'Archive Mode':13};
const abilityRewards={
 'First Feather':['feather-logo','Changes the logo-side bird icon to a feather.'],
 'On the Board':['theme-light','Unlocks the Theme selector and Light theme.'],
 'Something Uncommon':['font-garamond','Unlocks the Font selector and Garamond.'],
 'Full Spectrum':['spectrum','Adds a rarity-spectrum accent around acquired bird tiles.'],
 'Passport Stamps':['maltese','Translates the app interface, including the title, into Maltese.'],
 'Seen You Before':['eyes','Turns every O in the app interface into an eye emoji.'],
 'Field Journal':['theme-field','Unlocks Parchment and Khaki themes.'],
 'Local Explorer':['font-local','Unlocks Georgia and Typewriter fonts.']
};
let db=null,running=false,pending=false;
const norm=s=>String(s||'').trim().toLowerCase();
async function birds(){if(!db)db=await new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
const has=(b,n)=>b.some(x=>norm(x.commonName)===norm(n));
const sightings=(b,n)=>b.find(x=>norm(x.commonName)===norm(n))?.sightings?.length||0;
const contains=(b,words)=>b.filter(x=>words.some(w=>norm(x.commonName).includes(w))).length;
function extraChallenges(b){return[
{name:'Sydney Starter Pack',icon:'🦜',desc:'Find Rainbow Lorikeet, Sulphur-crested Cockatoo and Australian Magpie.',type:'points',reward:8,value:[has(b,'Rainbow Lorikeet'),has(b,'Sulphur-crested Cockatoo'),has(b,'Australian Magpie')].filter(Boolean).length,target:3},
{name:'Harbour Patrol',icon:'🌊',desc:'Find Silver Gull, Australian Pelican and Pied Cormorant.',type:'ability',reward:['ripple','Adds a subtle ripple effect to acquired tiles.'],value:[has(b,'Silver Gull'),has(b,'Australian Pelican'),has(b,'Pied Cormorant')].filter(Boolean).length,target:3},
{name:'After Dark',icon:'🦉',desc:'Find a Tawny Frogmouth.',type:'points',reward:12,value:has(b,'Tawny Frogmouth')?1:0,target:1},
{name:'Tiny Royalty',icon:'🧚',desc:'Find a Superb Fairywren.',type:'ability',reward:['rarity-glow','Adds a subtle glow to rarity dots.'],value:has(b,'Superb Fairywren')?1:0,target:1},
{name:'Indian Invasion',icon:'🐦',desc:'Find a Common Myna (Indian Myna).',type:'points',reward:3,value:(has(b,'Common Myna')||has(b,'Indian Myna'))?1:0,target:1},
{name:'Rock Around the Clock',icon:'🕊️',desc:'Record 15 Rock Dove sightings.',type:'ability',reward:['pigeon','Adds a tiny pigeon stamp beside repeat-sighting counts.'],value:sightings(b,'Rock Dove'),target:15},
{name:'Bin Chicken Initiation',icon:'🗑️',desc:'Find an Australian White Ibis.',type:'points',reward:2,value:has(b,'Australian White Ibis')?1:0,target:1},
{name:'Masked Menace',icon:'🎭',desc:'Find a Masked Lapwing.',type:'points',reward:3,value:has(b,'Masked Lapwing')?1:0,target:1},
{name:'Welcome Swallow',icon:'👋',desc:'Find a Welcome Swallow.',type:'ability',reward:['swallow','Adds a tiny swoop flourish when opening a bird card.'],value:has(b,'Welcome Swallow')?1:0,target:1},
{name:'Pelican Brief',icon:'📄',desc:'Find an Australian Pelican.',type:'points',reward:4,value:has(b,'Australian Pelican')?1:0,target:1},
{name:'Lorikeet Tax',icon:'🌈',desc:'Record 10 Rainbow Lorikeet sightings.',type:'points',reward:10,value:sightings(b,'Rainbow Lorikeet'),target:10},
{name:'Magpie Diplomacy',icon:'⚫',desc:'Record 10 Australian Magpie sightings.',type:'ability',reward:['magpie','Adds a monochrome accent option to acquired tiles.'],value:sightings(b,'Australian Magpie'),target:10},
{name:'Cormorant Committee',icon:'🌊',desc:'Collect 3 cormorant species.',type:'points',reward:14,value:contains(b,['cormorant']),target:3},
{name:'Honeyeater Union',icon:'🍯',desc:'Collect 5 honeyeaters, miners or wattlebirds.',type:'points',reward:15,value:contains(b,['honeyeater','miner','wattlebird']),target:5},
{name:'Duck Department',icon:'🦆',desc:'Collect 6 ducks or teal.',type:'points',reward:18,value:contains(b,['duck','teal','shoveler','shelduck']),target:6},
{name:'Kingfisher Cabinet',icon:'🐟',desc:'Collect 3 kingfishers or kookaburras.',type:'ability',reward:['kingfisher','Adds a blue family accent to kingfisher cards.'],value:contains(b,['kingfisher','kookaburra']),target:3},
{name:'Raptor Audit',icon:'🦅',desc:'Collect 4 raptors.',type:'points',reward:30,value:contains(b,['eagle','kite','hawk','falcon','goshawk','harrier','osprey']),target:4},
{name:'Parrot Problem',icon:'🦜',desc:'Collect 8 parrots, lorikeets, rosellas, corellas or cockatoos.',type:'ability',reward:['prism','Gives the points badge a subtle prismatic sheen.'],value:contains(b,['parrot','lorikeet','cockatoo','rosella','corella','galah']),target:8}
]}
function readState(){try{return JSON.parse(localStorage.getItem(STATE)||'{}')}catch{return{}}}
function saveState(s){localStorage.setItem(STATE,JSON.stringify(s));applyAbilities()}
function applyAbilities(){const s=readState(),unlocked=Object.entries(s).filter(([,v])=>v.unlocked).map(([k])=>k);localStorage.setItem('compendiumUnlockedAbilitiesV1',JSON.stringify(unlocked));document.documentElement.dataset.rewardRipple=s.ripple?.enabled?'on':'off';document.documentElement.dataset.rewardGlow=s['rarity-glow']?.enabled?'on':'off';document.documentElement.dataset.rewardPrism=s.prism?.enabled?'on':'off';document.documentElement.dataset.rewardSpectrum=s.spectrum?.enabled?'on':'off';const img=document.querySelector('.brand-bird');if(img){if(s['feather-logo']?.enabled){img.style.display='none';let f=document.getElementById('rewardFeather');if(!f){f=document.createElement('span');f.id='rewardFeather';f.textContent='🪶';f.style.fontSize='30px';img.after(f)}}else{img.style.display='';document.getElementById('rewardFeather')?.remove()}}dispatchEvent(new Event('achievement-abilities-changed'))}
function ensureCss(){if(document.getElementById('rewardStylesV72'))return;const s=document.createElement('style');s.id='rewardStylesV72';s.textContent='.reward-ability-icon{border:2px solid var(--muted);border-radius:13px;padding:6px;display:inline-flex!important}.reward-points{font-size:10px;font-weight:900;color:var(--muted);margin-left:7px}.reward-ability-preview{font-size:11px;color:var(--muted);margin:8px 0}.reward-toggle{margin-top:7px;border:1px solid var(--line);background:var(--bg);color:var(--text);border-radius:9px;padding:6px 9px;font-weight:800}html[data-reward-ripple="on"] .bird-tile:hover{transform:translateY(-2px) rotate(.2deg)}html[data-reward-glow="on"] .rarity-dot{filter:drop-shadow(0 0 5px currentColor)}html[data-reward-prism="on"] .points-counter{background:linear-gradient(110deg,var(--panel),color-mix(in srgb,#9b59ff 16%,var(--panel)),color-mix(in srgb,#36c66b 13%,var(--panel)))}html[data-reward-spectrum="on"] .bird-tile{outline:1px solid color-mix(in srgb,#a75cff 45%,transparent)}';document.head.appendChild(s)}
async function decorate(){if(running){pending=true;return}running=true;try{const v=document.getElementById('achievementsView');if(!v||getComputedStyle(v).display==='none')return;const b=await birds();let bonus=0,state=readState();v.querySelectorAll('.ach-card').forEach(c=>{if(c.closest('.species-achievements'))return;const name=c.querySelector('.ach-name')?.textContent?.trim(),done=c.classList.contains('done'),icon=c.querySelector('.ach-icon');if(!name||!icon)return;c.querySelectorAll('.reward-points,.reward-ability-preview,.reward-toggle').forEach(x=>x.remove());icon.classList.remove('reward-ability-icon');if(pointRewards[name]!=null){icon.insertAdjacentHTML('afterend',`<small class="reward-points">+${pointRewards[name]} pts</small>`);if(done)bonus+=pointRewards[name]}if(abilityRewards[name]){icon.classList.add('reward-ability-icon');const[id,desc]=abilityRewards[name];c.insertAdjacentHTML('beforeend',`<div class="reward-ability-preview"><b>Ability:</b> ${desc}</div>`);if(done&&!state[id])state[id]={unlocked:true,enabled:false};if(done){const bt=document.createElement('button');bt.className='reward-toggle';bt.textContent=state[id]?.enabled?'Enabled':'Disabled';bt.onclick=e=>{e.stopPropagation();const s=readState();s[id]={unlocked:true,enabled:!s[id]?.enabled};saveState(s);schedule()};c.appendChild(bt)}}});
const old=v.querySelector('.species-achievements');if(old)old.remove();const sec=document.createElement('section');sec.className='species-achievements';sec.innerHTML='<div class="ach-section-title">Sydney & species challenges</div><div class="ach-grid"></div>';const grid=sec.querySelector('.ach-grid');for(const g of extraChallenges(b)){const done=g.value>=g.target,pct=Math.min(100,Math.round(g.value/g.target*100)),card=document.createElement('article');card.className='ach-card'+(done?' done':'');let label;if(g.type==='points'){label=`+${g.reward} pts`;if(done)bonus+=g.reward}else{const[id,desc]=g.reward;label='Ability';if(done&&!state[id])state[id]={unlocked:true,enabled:false};card.dataset.ability=id;card.dataset.abilityDesc=desc}card.innerHTML=`${done?'<div class="ach-done-badge">Unlocked</div>':''}<div class="ach-icon-row"><span class="ach-icon ${g.type==='ability'?'reward-ability-icon':''}">${g.icon}</span><small class="reward-points">${label}</small></div><div class="ach-name">${g.name}</div><div class="ach-desc">${g.desc}</div>${g.type==='ability'?`<div class="reward-ability-preview"><b>Ability:</b> ${g.reward[1]}</div>`:''}<div class="ach-progress-row"><span>${Math.min(g.value,g.target)} / ${g.target}</span><span>${pct}%</span></div><div class="ach-bar"><div class="ach-bar-fill" style="width:${pct}%"></div></div>`;if(g.type==='ability'&&done){const[id]=g.reward,bt=document.createElement('button');bt.className='reward-toggle';bt.textContent=state[id]?.enabled?'Enabled':'Disabled';bt.onclick=e=>{e.stopPropagation();const s=readState();s[id]={unlocked:true,enabled:!s[id]?.enabled};saveState(s);schedule()};card.appendChild(bt)}grid.appendChild(card)}v.appendChild(sec);localStorage.setItem(STATE,JSON.stringify(state));localStorage.setItem(BONUS_KEY,String(bonus));dispatchEvent(new CustomEvent('achievement-points',{detail:{bonus}}));applyAbilities()}finally{running=false;if(pending){pending=false;setTimeout(decorate,80)}}}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(decorate,120)}
function init(){ensureCss();applyAbilities();addEventListener('open-achievements',()=>setTimeout(decorate,180));addEventListener('bird-local-change',schedule);document.addEventListener('click',e=>{if(e.target.closest?.('[data-comp-tab="achievements"]'))setTimeout(decorate,180)});setTimeout(()=>{const v=document.getElementById('achievementsView');if(v&&getComputedStyle(v).display!=='none')decorate()},900)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();