const RARITIES=[
 {key:"common",label:"Common",color:"#ff8a1f",rank:1},
 {key:"uncommon",label:"Uncommon",color:"#36c66b",rank:2},
 {key:"epic",label:"Epic",color:"#3f8cff",rank:3},
 {key:"mythical",label:"Mythical",color:"#a75cff",rank:4},
 {key:"legendary",label:"Legendary",color:"#f4c542",rank:5}
];
let db,birds=[],activeBirdId=null,editingBirdId=null,editingSightingId=null,selectedRarity="common",pendingCoverBlob=null,pendingSightingBlobs=[],pendingEditSightingBlobs=[],editingSightingWorkingPhotos=[],lastCoords=null;
const $=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10),rarityObj=k=>RARITIES.find(r=>r.key===k)||RARITIES[0],blobUrl=b=>b?URL.createObjectURL(b):"",makeId=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();

async function openDB(){db=await new Promise((res,rej)=>{const r=indexedDB.open("birdCompendiumDB",1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains("birds"))r.result.createObjectStore("birds",{keyPath:"id"})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const dbGetAll=()=>new Promise((res,rej)=>{const r=db.transaction("birds").objectStore("birds").getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const dbPut=b=>new Promise((res,rej)=>{const r=db.transaction("birds","readwrite").objectStore("birds").put(b);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const dbDelete=id=>new Promise((res,rej)=>{const r=db.transaction("birds","readwrite").objectStore("birds").delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});

function renderRarityPicker(){rarityPicker.innerHTML=RARITIES.map(r=>`<button type="button" class="rarity-option ${r.key===selectedRarity?"selected":""}" data-rarity="${r.key}"><span class="rarity-dot" style="background:${r.color}"></span><span>${r.label}</span></button>`).join("");rarityPicker.querySelectorAll(".rarity-option").forEach(b=>b.onclick=()=>{selectedRarity=b.dataset.rarity;renderRarityPicker()})}
function renderFilters(){rarityFilters.innerHTML=`<button class="filter-chip active" data-filter="all">All</button>`+RARITIES.map(r=>`<button class="filter-chip" data-filter="${r.key}"><span class="rarity-dot" style="background:${r.color}"></span>${r.label}</button>`).join("");rarityFilters.querySelectorAll(".filter-chip").forEach(b=>b.onclick=()=>{rarityFilters.querySelectorAll(".filter-chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()})}
function getFiltered(){const q=searchInput.value.trim().toLowerCase(),f=rarityFilters.querySelector(".active")?.dataset.filter||"all",s=sortSelect.value;let a=birds.filter(b=>(!q||b.commonName.toLowerCase().includes(q))&&(f==="all"||b.rarity===f));a.sort((x,y)=>s==="name-asc"?x.commonName.localeCompare(y.commonName):s==="name-desc"?y.commonName.localeCompare(x.commonName):s==="rarity-asc"?rarityObj(x.rarity).rank-rarityObj(y.rarity).rank:s==="rarity-desc"?rarityObj(y.rarity).rank-rarityObj(x.rarity).rank:s==="date-asc"?(x.createdAt||0)-(y.createdAt||0):(y.createdAt||0)-(x.createdAt||0));return a}
function render(){birdGrid.innerHTML="";summaryText.textContent=`${birds.length} ${birds.length===1?"species":"species"} discovered`;emptyState.classList.toggle("hidden",birds.length!==0);birdGrid.classList.toggle("hidden",birds.length===0);getFiltered().forEach(b=>{const n=birdTileTemplate.content.firstElementChild.cloneNode(true),im=n.querySelector(".tile-photo");im.src=b.coverPhoto?blobUrl(b.coverPhoto):"icon-512.png";if(!b.coverPhoto)im.classList.add("placeholder");n.querySelector(".tile-name").textContent=b.commonName;n.querySelector(".rarity-dot").style.background=rarityObj(b.rarity).color;const multi=n.querySelector(".multi-sighting-badge");if((b.sightings||[]).length>1)multi.classList.add("visible");n.onclick=()=>openDetail(b.id);birdGrid.appendChild(n)})}

function resetBirdForm(){editingBirdId=null;selectedRarity="common";pendingCoverBlob=null;lastCoords=null;birdDialogTitle.textContent="Add bird";commonNameInput.value="";commonNameInput.dataset.taxonId="";scientificNameInput.value="";birdNotesInput.value="";birdDateInput.value=today();birdLocationInput.value="";sightingNotesInput.value="";lookupStatus.textContent="";autoClassStatus.textContent="";birdPhotoPreview.removeAttribute("src");document.querySelector(".hero-picker").classList.remove("has-photo");document.querySelector(".first-sighting").style.display="grid";renderRarityPicker()}
function openAddBird(){resetBirdForm();birdDialog.showModal()}
async function reverseGeocode(lat,lon){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}`),j=await r.json();return j.display_name?.split(",").slice(0,3).join(",")||`${lat.toFixed(4)}, ${lon.toFixed(4)}`}catch{return `${lat.toFixed(4)}, ${lon.toFixed(4)}`}}
function useGPS(target){target.placeholder="Getting location…";navigator.geolocation.getCurrentPosition(async p=>{lastCoords={lat:p.coords.latitude,lon:p.coords.longitude};target.value=await reverseGeocode(lastCoords.lat,lastCoords.lon)},()=>target.placeholder="Location unavailable",{enableHighAccuracy:true,timeout:10000})}
async function lookupSpecies(){const q=commonNameInput.value.trim();if(!q)return;lookupStatus.textContent="Searching…";try{const r=await fetch(`https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(q)}&rank=species&per_page=8`),j=await r.json(),x=(j.results||[]).find(v=>(v.preferred_common_name||"").toLowerCase()===q.toLowerCase())||j.results?.[0];if(!x)throw 0;scientificNameInput.value=x.name||"";commonNameInput.value=x.preferred_common_name||q;commonNameInput.dataset.taxonId=x.id;lookupStatus.textContent="Matched via iNaturalist"}catch{lookupStatus.textContent="No confident match — enter manually"}}
async function suggestClass(){const id=commonNameInput.dataset.taxonId;if(!id){autoClassStatus.textContent="Look up the species first";return}if(!lastCoords){autoClassStatus.textContent="Getting your location…";await new Promise(res=>navigator.geolocation.getCurrentPosition(p=>{lastCoords={lat:p.coords.latitude,lon:p.coords.longitude};res()},()=>res(),{timeout:8000}))}if(!lastCoords){autoClassStatus.textContent="Location permission needed";return}autoClassStatus.textContent="Checking local observations…";try{const d=new Date();d.setFullYear(d.getFullYear()-5);const url=`https://api.inaturalist.org/v1/observations?taxon_id=${id}&lat=${lastCoords.lat}&lng=${lastCoords.lon}&radius=50&quality_grade=research&d1=${d.toISOString().slice(0,10)}&per_page=1`;const j=await(await fetch(url)).json(),n=j.total_results||0;selectedRarity=n>=500?"common":n>=120?"uncommon":n>=25?"epic":n>=4?"mythical":"legendary";renderRarityPicker();autoClassStatus.textContent=`Suggested from ${n.toLocaleString()} nearby records`}catch{autoClassStatus.textContent="Couldn’t check — choose manually"}}

async function saveBird(e){e.preventDefault();const name=commonNameInput.value.trim();if(!name){alert("Add a common name first.");return}let b;if(editingBirdId){b=birds.find(x=>x.id===editingBirdId);if(!b){alert("That bird could not be found. Close the editor and try again.");return}}else{b={id:makeId(),createdAt:Date.now(),sightings:[]};const s={id:makeId(),date:birdDateInput.value||today(),location:birdLocationInput.value.trim(),notes:sightingNotesInput.value.trim(),coords:lastCoords,photos:pendingCoverBlob?[pendingCoverBlob]:[]};if(s.location||s.notes||s.photos.length)b.sightings.push(s)}b.commonName=name;b.scientificName=scientificNameInput.value.trim();b.rarity=selectedRarity;b.notes=birdNotesInput.value.trim();if(pendingCoverBlob)b.coverPhoto=pendingCoverBlob;await dbPut(b);birds=await dbGetAll();const wasEditing=Boolean(editingBirdId);const id=b.id;birdDialog.close();editingBirdId=null;render();if(wasEditing)openDetail(id)}

function openDetail(id){activeBirdId=id;const b=birds.find(x=>x.id===id);if(!b)return;detailHero.src=b.coverPhoto?blobUrl(b.coverPhoto):"icon-512.png";detailCommonName.textContent=b.commonName;detailScientificName.textContent=b.scientificName?`(${b.scientificName})`:"";detailRarityDot.style.background=rarityObj(b.rarity).color;const pc=(b.sightings||[]).reduce((n,s)=>n+(s.photos?.length||0),0);detailMeta.textContent=`${rarityObj(b.rarity).label} • ${(b.sightings||[]).length} ${(b.sightings||[]).length===1?"sighting":"sightings"} • ${pc} ${pc===1?"photo":"photos"}`;detailNotes.textContent=b.notes||"";detailNotes.style.display=b.notes?"block":"none";sightingsList.innerHTML="";(b.sightings||[]).slice().sort((x,y)=>(y.date||"").localeCompare(x.date||"")).forEach(s=>{const n=sightingTemplate.content.firstElementChild.cloneNode(true);n.dataset.sightingId=s.id;n.querySelector(".sighting-date").textContent=s.date?new Date(s.date+"T12:00:00").toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"}):"Undated";n.querySelector(".sighting-location").textContent=s.location||"No location";n.querySelector(".sighting-notes").textContent=s.notes||"";const strip=n.querySelector(".sighting-photos");(s.photos||[]).forEach(ph=>{const w=document.createElement("div");w.className="photo-choice";const im=document.createElement("img");im.src=blobUrl(ph);const bt=document.createElement("button");bt.type="button";bt.className="tiny-cover-btn";bt.textContent="Use as main";bt.onclick=ev=>{ev.stopPropagation();setCoverPhoto(b,ph)};w.append(im,bt);strip.appendChild(w)});n.querySelector(".edit-sighting-btn").onclick=()=>openEditSighting(s.id);n.querySelector(".delete-sighting-btn").onclick=()=>deleteSighting(s.id);sightingsList.appendChild(n)});if(!detailDialog.open)detailDialog.showModal()}

function editBird(){const b=birds.find(x=>x.id===activeBirdId);if(!b)return;detailDialog.close();resetBirdForm();editingBirdId=b.id;selectedRarity=b.rarity;birdDialogTitle.textContent="Edit bird";commonNameInput.value=b.commonName;scientificNameInput.value=b.scientificName||"";birdNotesInput.value=b.notes||"";document.querySelector(".first-sighting").style.display="none";if(b.coverPhoto){pendingCoverBlob=b.coverPhoto;birdPhotoPreview.src=blobUrl(b.coverPhoto);document.querySelector(".hero-picker").classList.add("has-photo")}renderRarityPicker();birdDialog.showModal()}

async function deleteBird(){const b=birds.find(x=>x.id===activeBirdId);if(!b)return;if(!confirm(`Delete ${b.commonName} from the compendium?\n\nThis removes the bird card and every sighting stored inside it. This cannot be undone.`))return;await dbDelete(b.id);birds=await dbGetAll();activeBirdId=null;detailDialog.close();render()}
async function setCoverPhoto(b,ph){b.coverPhoto=ph;await dbPut(b);birds=await dbGetAll();detailHero.src=blobUrl(ph);render()}

function openSighting(){pendingSightingBlobs=[];lastCoords=null;sightingDateInput.value=today();sightingLocationInput.value="";sightingNotesInput2.value="";sightingPhotoStrip.innerHTML="";sightingDialog.showModal()}
async function saveSighting(e){e.preventDefault();const b=birds.find(x=>x.id===activeBirdId);if(!b)return;const s={id:makeId(),date:sightingDateInput.value||today(),location:sightingLocationInput.value.trim(),notes:sightingNotesInput2.value.trim(),coords:lastCoords,photos:pendingSightingBlobs.slice()};b.sightings=b.sightings||[];b.sightings.push(s);if(!b.coverPhoto&&s.photos.length)b.coverPhoto=s.photos[0];await dbPut(b);birds=await dbGetAll();sightingDialog.close();render();openDetail(b.id)}

function openEditSighting(id){const b=birds.find(x=>x.id===activeBirdId),s=b?.sightings?.find(x=>x.id===id);if(!s)return;editingSightingId=id;pendingEditSightingBlobs=[];editingSightingWorkingPhotos=[...(s.photos||[])];lastCoords=s.coords||null;editSightingDateInput.value=s.date||today();editSightingLocationInput.value=s.location||"";editSightingNotesInput.value=s.notes||"";editSightingNewPhotoStrip.innerHTML="";renderExistingEditPhotos(s);editSightingDialog.showModal()}
function renderExistingEditPhotos(s){editSightingExistingPhotos.innerHTML="";editingSightingWorkingPhotos.forEach((ph,index)=>{const w=document.createElement("div");w.className="photo-choice editing";const im=document.createElement("img");im.src=blobUrl(ph);const remove=document.createElement("button");remove.type="button";remove.className="remove-photo-btn";remove.textContent="×";remove.onclick=()=>{editingSightingWorkingPhotos.splice(index,1);renderExistingEditPhotos(s)};const main=document.createElement("button");main.type="button";main.className="tiny-cover-btn";main.textContent="Use as main";main.onclick=()=>{const b=birds.find(x=>x.id===activeBirdId);setCoverPhoto(b,ph)};w.append(im,remove,main);editSightingExistingPhotos.appendChild(w)})}
async function updateSighting(e){e.preventDefault();const b=birds.find(x=>x.id===activeBirdId),s=b?.sightings?.find(x=>x.id===editingSightingId);if(!s)return;s.date=editSightingDateInput.value||today();s.location=editSightingLocationInput.value.trim();s.notes=editSightingNotesInput.value.trim();s.coords=lastCoords||s.coords||null;s.photos=[...editingSightingWorkingPhotos,...pendingEditSightingBlobs];await dbPut(b);birds=await dbGetAll();editSightingDialog.close();editingSightingId=null;render();openDetail(b.id)}
async function deleteSighting(id){const b=birds.find(x=>x.id===activeBirdId),s=b?.sightings?.find(x=>x.id===id);if(!b||!s)return;if(!confirm("Delete this sighting? Its photos, date, location and notes will be removed."))return;b.sightings=b.sightings.filter(x=>x.id!==id);await dbPut(b);birds=await dbGetAll();render();openDetail(b.id)}

async function init(){await openDB();birds=await dbGetAll();renderFilters();renderRarityPicker();render();addBirdBtn.onclick=openAddBird;emptyAddBtn.onclick=openAddBird;searchInput.oninput=render;sortSelect.onchange=render;lookupBtn.onclick=lookupSpecies;autoClassBtn.onclick=suggestClass;useLocationBtn.onclick=()=>useGPS(birdLocationInput);sightingUseLocationBtn.onclick=()=>useGPS(sightingLocationInput);editSightingUseLocationBtn.onclick=()=>useGPS(editSightingLocationInput);saveBirdBtn.onclick=saveBird;closeDetailBtn.onclick=()=>detailDialog.close();editBirdBtn.onclick=editBird;deleteBirdBtn.onclick=deleteBird;addSightingBtn.onclick=openSighting;saveSightingBtn.onclick=saveSighting;updateSightingBtn.onclick=updateSighting;
birdPhotoInput.onchange=e=>{const f=e.target.files?.[0];if(!f)return;pendingCoverBlob=f.slice(0,f.size,f.type);birdPhotoPreview.src=URL.createObjectURL(f);document.querySelector(".hero-picker").classList.add("has-photo")};
sightingPhotosInput.onchange=e=>{pendingSightingBlobs=[...(e.target.files||[])].map(f=>f.slice(0,f.size,f.type));sightingPhotoStrip.innerHTML="";pendingSightingBlobs.forEach(b=>{const im=document.createElement("img");im.src=blobUrl(b);sightingPhotoStrip.appendChild(im)})};
editSightingPhotosInput.onchange=e=>{pendingEditSightingBlobs=[...(e.target.files||[])].map(f=>f.slice(0,f.size,f.type));editSightingNewPhotoStrip.innerHTML="";pendingEditSightingBlobs.forEach(b=>{const im=document.createElement("img");im.src=blobUrl(b);editSightingNewPhotoStrip.appendChild(im)})};
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}
init();
