(()=>{
const DB='birdCompendiumDB',STORE='birds';
let db=null,pendingAudio=null,pendingRemove=false,pendingSave=false,activeUrl=null,lastDetailKey='';
const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
function css(){if(document.getElementById('birdAudioStyles'))return;const s=document.createElement('style');s.id='birdAudioStyles';s.textContent=`
.bird-audio-field{display:grid;gap:8px}.bird-audio-field>span{color:var(--muted);font-size:13px}.bird-audio-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.bird-audio-input{max-width:100%;font-size:12px}.bird-audio-current{font-size:11px;color:var(--muted)}.bird-audio-remove{border:1px solid rgba(255,91,91,.35);background:rgba(105,20,20,.22);color:#ff9a9a;border-radius:10px;padding:7px 10px;font-weight:800}.bird-audio-detail{margin:12px 0 4px;padding:12px;border:1px solid var(--line);background:var(--panel);border-radius:14px}.bird-audio-detail-label{font-size:11px;font-weight:900;color:var(--muted);margin-bottom:8px}.bird-audio-detail audio{display:block;width:100%;min-height:38px}.bird-audio-play-fallback{display:none;border:1px solid var(--line);background:var(--panel2);color:var(--text);border-radius:10px;padding:8px 11px;font-weight:800;font-size:12px}.bird-audio-play-fallback.visible{display:inline-flex;align-items:center;gap:6px}
`;document.head.appendChild(s)}
async function openDB(){if(db)return db;db=await new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return db}
async function allBirds(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function getBird(id){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function putBird(b){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(b);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function resetState(){pendingAudio=null;pendingRemove=false;const input=document.getElementById('birdAudioInput');if(input)input.value='';updateCurrent(null)}
function ensureField(){const body=document.querySelector('#birdDialog .sheet-body');if(!body)return;let wrap=body.querySelector('.bird-audio-field');if(!wrap){wrap=document.createElement('label');wrap.className='bird-audio-field';wrap.innerHTML='<span>Audio recording <em>optional</em></span><div class="bird-audio-row"><input id="birdAudioInput" class="bird-audio-input" type="file" accept="audio/*,.m4a,.mp3,.wav,.aac,.ogg,.webm"><button id="birdAudioRemove" type="button" class="bird-audio-remove" style="display:none">Remove audio</button></div><div id="birdAudioCurrent" class="bird-audio-current"></div>';const notes=document.getElementById('birdNotesInput')?.closest('label');if(notes)body.insertBefore(wrap,notes);else body.appendChild(wrap);const input=wrap.querySelector('#birdAudioInput'),remove=wrap.querySelector('#birdAudioRemove');input.onchange=e=>{const f=e.target.files?.[0];pendingAudio=f?f.slice(0,f.size,f.type||'audio/mp4'):null;pendingRemove=false;updateCurrent(pendingAudio,'New recording selected')};remove.onclick=()=>{pendingAudio=null;pendingRemove=true;input.value='';updateCurrent(null,'Audio will be removed when you save')}}}
function updateCurrent(blob,msg=''){const cur=document.getElementById('birdAudioCurrent'),rm=document.getElementById('birdAudioRemove');if(!cur||!rm)return;cur.textContent=msg||(blob?`Current recording • ${Math.max(1,Math.round(blob.size/1024))} KB`:'No recording attached');rm.style.display=blob||pendingRemove?'inline-block':'none'}
async function currentFormBird(){const common=document.getElementById('commonNameInput')?.value||'',scientific=document.getElementById('scientificNameInput')?.value||'';const birds=await allBirds();return birds.find(b=>(scientific&&norm(b.scientificName)===norm(scientific))||norm(b.commonName)===norm(common))||null}
async function prepareAdd(){ensureField();resetState()}
async function prepareEdit(){ensureField();pendingAudio=null;pendingRemove=false;const b=await currentFormBird();const input=document.getElementById('birdAudioInput');if(input)input.value='';updateCurrent(b?.userAudio||null)}
async function patchSaved(id){if(!pendingSave||!id)return;const change=pendingSave;pendingSave=false;const b=await getBird(id);if(!b)return;if(change.remove)delete b.userAudio;else if(change.audio)b.userAudio=change.audio;else return;await putBird(b);window.dispatchEvent(new CustomEvent('bird-local-change',{detail:{type:'put',id:b.id,source:'bird-audio'}}));pendingAudio=null;pendingRemove=false;setTimeout(()=>decorateDetail(true),120)}
async function detailBird(){const common=document.getElementById('detailCommonName')?.textContent||'',scientific=String(document.getElementById('detailScientificName')?.textContent||'').replace(/[()]/g,'');const birds=await allBirds();return birds.find(b=>(scientific&&norm(b.scientificName)===norm(scientific))||norm(b.commonName)===norm(common))||null}
function cleanupPlayer(){document.querySelector('#detailDialog .bird-audio-detail')?.remove();if(activeUrl){URL.revokeObjectURL(activeUrl);activeUrl=null}lastDetailKey=''}
async function decorateDetail(force=false){const dialog=document.getElementById('detailDialog'),content=dialog?.querySelector('.detail-content');if(!dialog?.open||!content)return;const b=await detailBird();const key=b?.id||'';if(!force&&key&&key===lastDetailKey&&content.querySelector('.bird-audio-detail'))return;cleanupPlayer();if(!b?.userAudio)return;lastDetailKey=key;const blob=b.userAudio instanceof Blob?b.userAudio:new Blob([b.userAudio],{type:'audio/mp4'});activeUrl=URL.createObjectURL(blob);const box=document.createElement('div');box.className='bird-audio-detail';box.innerHTML='<div class="bird-audio-detail-label">Your recording</div>';const a=document.createElement('audio');a.controls=true;a.preload='metadata';a.playsInline=true;a.src=activeUrl;const fallback=document.createElement('button');fallback.type='button';fallback.className='bird-audio-play-fallback';fallback.textContent='▶ Play recording';fallback.onclick=async()=>{try{await a.play()}catch{}};a.addEventListener('error',()=>fallback.classList.add('visible'));box.append(a,fallback);const anchor=document.querySelector('#detailDialog .confidence-card-label')||document.getElementById('detailMeta');if(anchor)anchor.insertAdjacentElement('afterend',box);else content.prepend(box);setTimeout(()=>{if(a.readyState===0)fallback.classList.add('visible')},500)}
function init(){css();ensureField();document.addEventListener('click',e=>{if(e.target.closest?.('#addBirdBtn,#emptyAddBtn'))setTimeout(prepareAdd,0);if(e.target.closest?.('#editBirdBtn'))setTimeout(prepareEdit,40);if(e.target.closest?.('#saveBirdBtn'))pendingSave={audio:pendingAudio,remove:pendingRemove};if(e.target.closest?.('.bird-tile')){setTimeout(()=>decorateDetail(true),80);setTimeout(()=>decorateDetail(true),220)}});window.addEventListener('bird-local-change',e=>{if(e.detail?.type==='put'&&pendingSave)setTimeout(()=>patchSaved(e.detail.id),180);if(document.getElementById('detailDialog')?.open)setTimeout(()=>decorateDetail(true),160)});const detail=document.getElementById('detailDialog');detail?.addEventListener('close',cleanupPlayer);if(detail){new MutationObserver(()=>{if(detail.open)setTimeout(()=>decorateDetail(true),50)}).observe(detail,{attributes:true,attributeFilter:['open']})}addEventListener('focus',()=>{if(document.getElementById('detailDialog')?.open)decorateDetail(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&document.getElementById('detailDialog')?.open)decorateDetail(true)});setTimeout(()=>{if(document.getElementById('detailDialog')?.open)decorateDetail(true)},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();