(()=>{
const API='https://xeno-canto.org/api/2/recordings?query=';
let currentAudio=null,currentButton=null,cache=new Map();
function css(){if(document.getElementById('birdSoundStylesV78'))return;const s=document.createElement('style');s.id='birdSoundStylesV78';s.textContent=`.bird-sound-detail-wrap{display:flex;align-items:center;gap:7px;margin:8px 0 3px}.bird-sound-detail{width:34px;height:34px;border-radius:999px;border:1px solid var(--line);background:var(--panel2);color:var(--text);display:grid;place-items:center;font-size:16px;padding:0;flex:0 0 auto}.bird-sound-detail:active{transform:scale(.95)}.bird-sound-detail.loading{opacity:.62}.bird-sound-credit{font-size:10px;line-height:1.25;color:var(--muted);max-width:260px}`;document.head.appendChild(s)}
function cleanScientific(){return String(document.getElementById('detailScientificName')?.textContent||'').replace(/[()]/g,'').trim()}
function common(){return String(document.getElementById('detailCommonName')?.textContent||'').trim()}
function stop(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}if(currentButton){currentButton.textContent='🔊';currentButton.setAttribute('aria-label','Play bird sound');currentButton.classList.remove('loading');currentButton=null}}
function score(r){const q={A:50,B:40,C:30,D:20,E:10,'no score':0}[r.q]??0,typical=/song|call|vocal/i.test(r.type||'')?8:0,clean=!String(r.also||'').trim()?6:0,australia=String(r.cnt||'').toLowerCase()==='australia'?4:0;return q+typical+clean+australia}
async function findRecording(scientific,name){const key=scientific||name;if(cache.has(key))return cache.get(key);let query='';if(scientific){const parts=scientific.split(/\s+/);query=parts.length>=2?`gen:${parts[0]} sp:${parts[1]}`:scientific}else query=name;const r=await fetch(API+encodeURIComponent(query));if(!r.ok)throw new Error('Sound source unavailable');const j=await r.json(),rows=(j.recordings||[]).filter(x=>x.file);if(!rows.length)throw new Error('No recording found');rows.sort((a,b)=>score(b)-score(a));cache.set(key,rows[0]);return rows[0]}
function fileUrl(r){let f=String(r.file||'');if(f.startsWith('//'))f='https:'+f;else if(f.startsWith('/'))f='https://xeno-canto.org'+f;return f}
function creditText(r){const bits=[];if(r.rec)bits.push(r.rec);bits.push('xeno-canto');if(r.q)bits.push(`quality ${r.q}`);return bits.join(' • ')}
async function play(btn,credit){if(currentButton===btn&&currentAudio){stop();return}stop();btn.classList.add('loading');btn.textContent='…';credit.textContent='Finding a high-quality species recording…';try{const rec=await findRecording(cleanScientific(),common()),src=fileUrl(rec);if(!src)throw 0;const audio=new Audio(src);audio.preload='none';currentAudio=audio;currentButton=btn;audio.onplaying=()=>{btn.classList.remove('loading');btn.textContent='⏹';btn.setAttribute('aria-label','Stop bird sound');credit.textContent=creditText(rec)};audio.onended=stop;audio.onerror=()=>{credit.textContent='Sound could not be played right now.';stop()};await audio.play()}catch{btn.classList.remove('loading');btn.textContent='🔊';credit.textContent='No reliable playable recording found for this species.';currentAudio=null;currentButton=null}}
function ensureDetailButton(reset=false){const content=document.querySelector('#detailDialog .detail-content'),meta=document.getElementById('detailMeta');if(!content||!meta)return;let wrap=content.querySelector('.bird-sound-detail-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='bird-sound-detail-wrap';const btn=document.createElement('button');btn.type='button';btn.className='bird-sound-detail';btn.textContent='🔊';btn.setAttribute('aria-label','Play bird sound');btn.title='Play a representative species sound';const credit=document.createElement('span');credit.className='bird-sound-credit';btn.onclick=e=>{e.preventDefault();e.stopPropagation();play(btn,credit)};wrap.append(btn,credit);meta.insertAdjacentElement('afterend',wrap)}else if(reset){stop();const btn=wrap.querySelector('.bird-sound-detail'),credit=wrap.querySelector('.bird-sound-credit');if(btn){btn.textContent='🔊';btn.classList.remove('loading')}if(credit)credit.textContent=''}}
function init(){css();document.querySelectorAll('.bird-sound-btn').forEach(x=>x.remove());ensureDetailButton(false);const dialog=document.getElementById('detailDialog');if(dialog)dialog.addEventListener('close',stop);document.addEventListener('click',e=>{if(e.target.closest?.('.bird-tile'))setTimeout(()=>ensureDetailButton(true),80)});addEventListener('bird-local-change',()=>setTimeout(()=>ensureDetailButton(false),100))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();