(()=>{
const COMMONS='https://commons.wikimedia.org/w/api.php';
let currentAudio=null,currentButton=null,cache=new Map();
function css(){if(document.getElementById('birdSoundStylesV79'))return;const s=document.createElement('style');s.id='birdSoundStylesV79';s.textContent=`.bird-sound-detail-wrap{display:flex;align-items:center;gap:7px;margin:8px 0 3px}.bird-sound-detail{width:34px;height:34px;border-radius:999px;border:1px solid var(--line);background:var(--panel2);color:var(--text);display:grid;place-items:center;font-size:16px;padding:0;flex:0 0 auto}.bird-sound-detail:active{transform:scale(.95)}.bird-sound-detail.loading{opacity:.62}.bird-sound-credit{font-size:10px;line-height:1.25;color:var(--muted);max-width:280px}`;document.head.appendChild(s)}
function cleanScientific(){return String(document.getElementById('detailScientificName')?.textContent||'').replace(/[()]/g,'').trim()}
function common(){return String(document.getElementById('detailCommonName')?.textContent||'').trim()}
function stop(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}if(currentButton){currentButton.textContent='🔊';currentButton.setAttribute('aria-label','Play bird sound');currentButton.classList.remove('loading');currentButton=null}}
function cleanHtml(v){const d=document.createElement('div');d.innerHTML=String(v||'');return(d.textContent||'').trim()}
function scorePage(p,scientific,name){const title=String(p.title||'').toLowerCase(),info=p.imageinfo?.[0]||{},meta=info.extmetadata||{};let s=0;if(scientific&&title.includes(scientific.toLowerCase()))s+=60;if(name&&title.includes(name.toLowerCase()))s+=50;if(/bird|song|call|vocal|sound|voice/.test(title))s+=20;if(/juvenile|chick|nestling/.test(title))s-=15;if(info.mime?.startsWith('audio/'))s+=100;const desc=cleanHtml(meta.ImageDescription?.value).toLowerCase();if(scientific&&desc.includes(scientific.toLowerCase()))s+=25;if(name&&desc.includes(name.toLowerCase()))s+=20;return s}
async function commonsSearch(q,scientific,name){const u=new URL(COMMONS);u.searchParams.set('action','query');u.searchParams.set('format','json');u.searchParams.set('origin','*');u.searchParams.set('generator','search');u.searchParams.set('gsrnamespace','6');u.searchParams.set('gsrlimit','30');u.searchParams.set('gsrsearch',q);u.searchParams.set('prop','imageinfo');u.searchParams.set('iiprop','url|mime|extmetadata');const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('Commons search unavailable');const j=await r.json(),pages=Object.values(j.query?.pages||{}).filter(p=>p.imageinfo?.[0]?.mime?.startsWith('audio/')&&p.imageinfo?.[0]?.url);pages.sort((a,b)=>scorePage(b,scientific,name)-scorePage(a,scientific,name));return pages[0]||null}
async function findRecording(scientific,name){const key=(scientific||name).toLowerCase();if(cache.has(key))return cache.get(key);const queries=[];if(scientific){queries.push(`"${scientific}" bird call`, `"${scientific}" bird song`, `"${scientific}"`)}if(name){queries.push(`"${name}" bird call`, `"${name}" bird song`, `"${name}"`)}let best=null;for(const q of queries){try{const p=await commonsSearch(q,scientific,name);if(p){best=p;break}}catch{}}if(!best)throw new Error('No recording found');const i=best.imageinfo[0],m=i.extmetadata||{};const rec={file:i.url,title:best.title.replace(/^File:/,''),creator:cleanHtml(m.Artist?.value||m.Credit?.value||''),license:cleanHtml(m.LicenseShortName?.value||''),source:'Wikimedia Commons'};cache.set(key,rec);return rec}
function creditText(r){const bits=[];if(r.creator)bits.push(r.creator);bits.push(r.source);if(r.license)bits.push(r.license);return bits.join(' • ')}
async function play(btn,credit){if(currentButton===btn&&currentAudio){stop();return}stop();btn.classList.add('loading');btn.textContent='…';credit.textContent='Finding a representative species recording…';try{const rec=await findRecording(cleanScientific(),common()),src=rec.file;if(!src)throw 0;const audio=new Audio(src);audio.preload='metadata';currentAudio=audio;currentButton=btn;audio.onplaying=()=>{btn.classList.remove('loading');btn.textContent='⏹';btn.setAttribute('aria-label','Stop bird sound');credit.textContent=creditText(rec)};audio.onended=stop;audio.onerror=()=>{credit.textContent='That recording could not be played. Tap again to retry.';stop();cache.delete((cleanScientific()||common()).toLowerCase())};await audio.play()}catch{btn.classList.remove('loading');btn.textContent='🔊';credit.textContent='No playable reference recording found for this species yet.';currentAudio=null;currentButton=null}}
function ensureDetailButton(reset=false){const content=document.querySelector('#detailDialog .detail-content'),meta=document.getElementById('detailMeta');if(!content||!meta)return;let wrap=content.querySelector('.bird-sound-detail-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='bird-sound-detail-wrap';const btn=document.createElement('button');btn.type='button';btn.className='bird-sound-detail';btn.textContent='🔊';btn.setAttribute('aria-label','Play bird sound');btn.title='Play a representative species sound';const credit=document.createElement('span');credit.className='bird-sound-credit';btn.onclick=e=>{e.preventDefault();e.stopPropagation();play(btn,credit)};wrap.append(btn,credit);meta.insertAdjacentElement('afterend',wrap)}else if(reset){stop();const btn=wrap.querySelector('.bird-sound-detail'),credit=wrap.querySelector('.bird-sound-credit');if(btn){btn.textContent='🔊';btn.classList.remove('loading')}if(credit)credit.textContent=''}}
function init(){css();document.querySelectorAll('.bird-sound-btn').forEach(x=>x.remove());ensureDetailButton(false);const dialog=document.getElementById('detailDialog');if(dialog)dialog.addEventListener('close',stop);document.addEventListener('click',e=>{if(e.target.closest?.('.bird-tile'))setTimeout(()=>ensureDetailButton(true),80)});addEventListener('bird-local-change',()=>setTimeout(()=>ensureDetailButton(false),100))}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();