(()=>{
const URL="https://yfkbacnbprdmduymjjor.supabase.co",KEY="sb_publishable_HRLQSpf6osRgRiGdCC8QnA_ZGzKXknT";
const sb=window.supabase.createClient(URL,KEY);let user=null,busy=false;
const DB="birdCompendiumDB",STORE="birds",META="birdCloudMetaV7",SKIP="birdCloudSkipAutoOnce";
const loadMeta=()=>{try{return JSON.parse(localStorage.getItem(META)||"{}")}catch{return {}}},saveMeta=m=>localStorage.setItem(META,JSON.stringify(m));
function injectUI(){const css=document.createElement("style");css.textContent=`.cloud-sync-btn{border:1px solid #2d3338;background:#171a1d;color:#f5f6f7;border-radius:14px;padding:10px 13px;font-weight:700;margin-right:8px}.cloud-sync-btn.ok{border-color:#36c66b}.cloud-panel{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.72);display:none;align-items:flex-end;justify-content:center}.cloud-panel.open{display:flex}.cloud-sheet{width:min(620px,100%);background:#171a1d;color:#f5f6f7;border-radius:24px 24px 0 0;padding:18px;padding-bottom:max(24px,env(safe-area-inset-bottom))}.cloud-sheet input{width:100%;margin:6px 0 12px;background:#101214;border:1px solid #2d3338;border-radius:13px;color:#fff;padding:12px}.cloud-row{display:flex;gap:8px;flex-wrap:wrap}.cloud-sheet button{border:1px solid #2d3338;background:#202428;color:#fff;border-radius:12px;padding:10px 13px}.cloud-sheet .primary{background:#f5f6f7;color:#101214}.cloud-muted{color:#9aa1a8;font-size:13px}.cloud-head{display:flex;justify-content:space-between;align-items:center}.cloud-hidden{display:none!important}`;document.head.appendChild(css);const add=document.getElementById("addBirdBtn"),btn=document.createElement("button");btn.id="cloudBtn";btn.className="cloud-sync-btn";btn.textContent="Sync";add.parentNode.insertBefore(btn,add);const panel=document.createElement("div");panel.id="cloudPanel";panel.className="cloud-panel";panel.innerHTML=`<div class="cloud-sheet"><div class="cloud-head"><h2>Cloud Sync</h2><button id="cloudClose">Close</button></div><div id="cloudOut"><p class="cloud-muted">Use the same account on your iPhone and laptop.</p><input id="cloudEmail" name="bird-cloud-email" type="email" autocomplete="username" placeholder="Email"><input id="cloudPass" name="bird-cloud-password" type="password" autocomplete="current-password" placeholder="Password"><div class="cloud-row"><button class="primary" id="cloudSignIn">Sign in</button><button id="cloudSignUp">Create account</button></div></div><div id="cloudIn" class="cloud-hidden"><p>Signed in as <strong id="cloudWho"></strong></p><p id="cloudStatus" class="cloud-muted">Ready.</p><div class="cloud-row"><button class="primary" id="cloudNow">Sync now</button><button id="cloudSignOut">Sign out</button></div></div><p id="cloudAuthStatus" class="cloud-muted"></p></div>`;document.body.appendChild(panel);btn.onclick=()=>panel.classList.add("open");cloudClose.onclick=()=>panel.classList.remove("open");cloudSignIn.onclick=signIn;cloudSignUp.onclick=signUp;cloudSignOut.onclick=signOut;cloudNow.onclick=sync;}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getAll(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function putLocal(b){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).put(b);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function deleteLocal(id){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function fingerprint(b){const parts=[b.commonName,b.scientificName,b.country,b.rarity,b.notes,b.createdAt,b.coverPhoto?.size,b.coverPhoto?.type];for(const s of b.sightings||[])parts.push(s.id,s.date,s.location,s.notes,JSON.stringify(s.coords),...(s.photos||[]).flatMap(p=>[p.size,p.type,p.lastModified]));const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(parts.join("|")));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function upload(blob,path){if(!blob)return null;const {error}=await sb.storage.from("bird-photos").upload(path,blob,{upsert:true,contentType:blob.type||"image/jpeg"});if(error)throw error;return path}
async function serialize(b){const p={id:b.id,commonName:b.commonName,scientificName:b.scientificName||"",country:b.country||"",rarity:b.rarity,notes:b.notes||"",createdAt:b.createdAt||Date.now(),sightings:[],coverPhotoPath:null};if(b.coverPhoto)p.coverPhotoPath=await upload(b.coverPhoto,`${user.id}/${b.id}/cover.jpg`);for(const s of b.sightings||[]){const x={id:s.id,date:s.date||"",location:s.location||"",notes:s.notes||"",coords:s.coords||null,photoPaths:[]};for(let i=0;i<(s.photos||[]).length;i++)x.photoPaths.push(await upload(s.photos[i],`${user.id}/${b.id}/${s.id}-${i}.jpg`));p.sightings.push(x)}return p}
async function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function download(path){if(!path)return null;let lastErr;for(let i=0;i<3;i++){try{const {data,error}=await sb.storage.from("bird-photos").download(path);if(error)throw error;if(!data||!data.size)throw new Error("Empty photo download");return data}catch(e){lastErr=e;await sleep(350*(i+1))}}const {data:signed,error:signedErr}=await sb.storage.from("bird-photos").createSignedUrl(path,60);if(!signedErr&&signed?.signedUrl){const r=await fetch(signed.signedUrl,{cache:"no-store"});if(r.ok){const blob=await r.blob();if(blob.size)return blob}}throw lastErr||signedErr||new Error("Photo download failed")}
function remoteHasPhotos(p){return Boolean(p?.coverPhotoPath||(p?.sightings||[]).some(s=>(s.photoPaths||[]).length))}
function localMissingRemotePhotos(local,p){if(p?.coverPhotoPath&&!local?.coverPhoto)return true;const ls=new Map((local?.sightings||[]).map(s=>[s.id,s]));return (p?.sightings||[]).some(s=>(s.photoPaths||[]).length>(ls.get(s.id)?.photos||[]).length)}
async function hydrate(r,oldLocal=null){const p=r.payload,b={id:p.id,commonName:p.commonName,scientificName:p.scientificName||"",country:p.country||"",rarity:p.rarity||"common",notes:p.notes||"",createdAt:p.createdAt||Date.now(),sightings:[]};if(p.coverPhotoPath){b.coverPhoto=await download(p.coverPhotoPath)}else if(oldLocal?.coverPhoto)b.coverPhoto=oldLocal.coverPhoto;for(const s of p.sightings||[]){const oldS=oldLocal?.sightings?.find(x=>x.id===s.id),x={id:s.id,date:s.date||"",location:s.location||"",notes:s.notes||"",coords:s.coords||null,photos:[]};for(const path of s.photoPaths||[])x.photos.push(await download(path));if(!(s.photoPaths||[]).length&&oldS?.photos?.length)x.photos=oldS.photos;x.photos=x.photos.filter(Boolean);b.sightings.push(x)}return b}
async function push(b,when=Date.now()){const payload=await serialize(b);const {error}=await sb.from("cloud_birds").upsert({id:b.id,user_id:user.id,payload,updated_at:new Date(when).toISOString()});if(error)throw error;return when}
async function directDelete(id){if(!user)return;const when=new Date().toISOString();const {error:tErr}=await sb.from("cloud_bird_deletions").upsert({user_id:user.id,bird_id:id,deleted_at:when});if(tErr){console.error(tErr);return}const {error:dErr}=await sb.from("cloud_birds").delete().eq("id",id).eq("user_id",user.id);if(dErr)console.error(dErr);const m=loadMeta();delete m[id];saveMeta(m)}
async function directPut(id){if(!user)return;const b=(await getAll()).find(x=>x.id===id);if(!b)return;await sb.from("cloud_bird_deletions").delete().eq("bird_id",id).eq("user_id",user.id);const when=await push(b);const m=loadMeta();m[id]={fingerprint:await fingerprint(b),remoteUpdated:when};saveMeta(m)}
async function sync(){if(!user||busy)return;busy=true;cloudStatus.textContent="Syncing…";let changed=false;try{const local=await getAll(),m=loadMeta();const [birdsRes,delRes]=await Promise.all([sb.from("cloud_birds").select("id,payload,updated_at").eq("user_id",user.id),sb.from("cloud_bird_deletions").select("bird_id,deleted_at").eq("user_id",user.id)]);if(birdsRes.error)throw birdsRes.error;if(delRes.error)throw delRes.error;const deleted=new Map((delRes.data||[]).map(x=>[x.bird_id,new Date(x.deleted_at).getTime()])),remote=new Map((birdsRes.data||[]).map(r=>[r.id,r]));let localMap=new Map(local.map(b=>[b.id,b]));for(const [id] of deleted){if(localMap.has(id)){await deleteLocal(id);localMap.delete(id);changed=true}delete m[id]}
for(const [id,r] of remote){if(deleted.has(id))continue;const localBird=localMap.get(id),rt=new Date(r.updated_at).getTime(),prev=m[id];if(!localBird){const fresh=await hydrate(r);await putLocal(fresh);m[id]={fingerprint:await fingerprint(fresh),remoteUpdated:rt};changed=true;continue}const fp=await fingerprint(localBird),needsPhotos=remoteHasPhotos(r.payload)&&localMissingRemotePhotos(localBird,r.payload);if(needsPhotos){const fresh=await hydrate(r,localBird);await putLocal(fresh);m[id]={fingerprint:await fingerprint(fresh),remoteUpdated:rt};changed=true;continue}if(!prev){const fresh=await hydrate(r,localBird);await putLocal(fresh);m[id]={fingerprint:await fingerprint(fresh),remoteUpdated:rt};changed=true}else if(rt>(prev.remoteUpdated||0)&&fp===prev.fingerprint){const fresh=await hydrate(r,localBird);await putLocal(fresh);m[id]={fingerprint:await fingerprint(fresh),remoteUpdated:rt};changed=true}else if(fp!==prev.fingerprint){const when=await push(localBird);m[id]={fingerprint:fp,remoteUpdated:when}}}
for(const [id,b] of localMap){if(deleted.has(id)||remote.has(id))continue;const when=await push(b);m[id]={fingerprint:await fingerprint(b),remoteUpdated:when}}
saveMeta(m);cloudStatus.textContent="Synced.";cloudBtn.classList.add("ok");cloudBtn.textContent="Synced";if(changed){sessionStorage.setItem(SKIP,"1");location.reload()}}catch(e){console.error(e);cloudStatus.textContent="Sync failed — retrying next sync. Local data is safe."}finally{busy=false}}
async function authUI(){const {data:{session}}=await sb.auth.getSession();user=session?.user||null;cloudOut.classList.toggle("cloud-hidden",!!user);cloudIn.classList.toggle("cloud-hidden",!user);if(user){cloudWho.textContent=user.email||"";cloudBtn.textContent="Synced";cloudBtn.classList.add("ok");if(sessionStorage.getItem(SKIP)==="1")sessionStorage.removeItem(SKIP);else await sync()}else{cloudBtn.textContent="Sync";cloudBtn.classList.remove("ok")}}
async function signIn(){cloudAuthStatus.textContent="Signing in…";const {error}=await sb.auth.signInWithPassword({email:cloudEmail.value.trim(),password:cloudPass.value});cloudAuthStatus.textContent=error?error.message:"";if(!error)await authUI()}
async function signUp(){cloudAuthStatus.textContent="Creating account…";const {data,error}=await sb.auth.signUp({email:cloudEmail.value.trim(),password:cloudPass.value});cloudAuthStatus.textContent=error?error.message:(data.session?"Account created.":"Account created — check your email if confirmation is required.");if(!error)await authUI()}
async function signOut(){await sb.auth.signOut();user=null;await authUI()}
window.addEventListener("bird-local-change",e=>{const d=e.detail||{};if(d.type==="delete")directDelete(d.id);else if(d.type==="put")setTimeout(()=>directPut(d.id),0)});
window.addEventListener("load",async()=>{injectUI();await authUI();setInterval(()=>{if(user&&!busy&&document.visibilityState==="visible")sync()},8000)});
})();