(()=>{
const DB="birdCompendiumDB",STORE="birds";
const IOC_PROXY="https://r.jina.ai/http://www.worldbirdnames.org/new/classification/family-index-2/";
const FAMILY_CACHE="compendiumIocFamiliesV15_2";
const BIRD_FAMILY_CACHE="compendiumBirdFamilyCacheV1";
const SPECIES_CACHE_PREFIX="compendiumFamilySpeciesV2:";
const RARITY={common:{label:"Common",color:"#ff8a1f",rank:1},uncommon:{label:"Uncommon",color:"#36c66b",rank:2},epic:{label:"Epic",color:"#3f8cff",rank:3},mythical:{label:"Mythical",color:"#a75cff",rank:4},legendary:{label:"Legendary",color:"#f4c542",rank:5}};
let families=[],owned=[],familyMapCache={};
const esc=s=>String(s??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s||"").trim().toLowerCase();
const blobUrl=b=>b?URL.createObjectURL(b):"";
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getBirds(){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function readJSON(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}
function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function suggestedRarity(count){const n=Number(count)||0;return n>=50000?"common":n>=10000?"uncommon":n>=2000?"epic":n>=300?"mythical":"legendary"}
function rarityFor(item){return item.bird?.rarity&&RARITY[item.bird.rarity]?item.bird.rarity:suggestedRarity(item.sp.observations)}

function injectStyles(){const s=document.createElement("style");s.textContent=`
.comp-nav{display:flex;gap:8px;align-items:center;margin:8px 0 18px;border-bottom:1px solid var(--line);padding-bottom:8px}.comp-nav-btn{border:0;background:transparent;color:var(--muted);padding:9px 13px;border-radius:12px;font-weight:800;font-size:15px}.comp-nav-btn.active{background:var(--panel2);color:var(--text)}
#familiesView{display:none}.families-head{display:flex;gap:12px;justify-content:space-between;align-items:end;margin:8px 0 14px;flex-wrap:wrap}.families-head h2{margin:0;font-size:26px}.families-head p{margin:3px 0 0}.families-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.families-controls select,.family-search{background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:12px;padding:9px 12px;font-weight:700}.family-search{min-width:220px;font-weight:500;outline:none}.family-search:focus{border-color:var(--muted)}
.family-list{border-top:1px solid var(--line)}.family-row{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:14px 3px;border-bottom:1px solid var(--line);cursor:pointer;user-select:text}.family-row:hover{background:color-mix(in srgb,var(--panel) 70%,transparent)}.family-row-main{min-width:0}.family-en{font-weight:800;font-size:16px}.family-la{font-style:italic;color:var(--muted);font-size:13px;margin-top:2px}.family-progress{white-space:nowrap;color:var(--muted);font-size:12px}.family-progress.has{color:var(--text);font-weight:800}.family-chevron{font-size:20px;color:var(--muted)}
.family-detail-head{display:flex;align-items:center;gap:10px;margin:7px 0 16px}.family-back{border:1px solid var(--line);background:var(--panel);color:var(--text);width:40px;height:40px;border-radius:12px;font-size:22px}.family-detail-title h2{margin:0}.family-detail-title p{margin:2px 0 0;color:var(--muted);font-style:italic}.family-status{color:var(--muted);font-size:13px;margin:8px 0 14px}
.family-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(175px,1fr));gap:12px}.family-species-tile{min-height:190px;border:1px solid var(--line);background:var(--panel);border-radius:18px;overflow:hidden;position:relative;color:var(--text);text-align:left;padding:0;display:flex;flex-direction:column}.family-species-photo{height:135px;width:100%;object-fit:cover;background:var(--panel2)}.family-species-info{padding:10px 11px 12px}.family-species-name{font-weight:850;line-height:1.12}.family-species-scientific{font-size:12px;font-style:italic;color:var(--muted);margin-top:3px}.family-species-meta{font-size:11px;color:var(--muted);margin-top:5px}.family-species-tile.unknown{align-items:stretch}.unknown-box{height:135px;background:var(--panel2);display:flex;align-items:center;justify-content:center;font-size:52px;font-weight:900;color:var(--muted)}.family-owned-badge{position:absolute;top:8px;right:8px;background:rgba(0,0,0,.66);color:white;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.family-rarity{display:flex;align-items:center;gap:6px;margin-top:7px;font-size:11px;font-weight:800}.family-rarity-dot{width:10px;height:10px;border-radius:50%;display:inline-block;box-shadow:0 0 0 1px rgba(255,255,255,.16)}.family-rarity.suggested{color:var(--muted);font-weight:650}.families-source{font-size:11px;color:var(--muted);margin:14px 0 4px}.family-empty-search{padding:24px 3px;color:var(--muted)}
@media(max-width:700px){.comp-nav{margin-top:4px}.families-head{align-items:flex-start}.families-controls{width:100%}.family-search{min-width:0;flex:1 1 100%}.family-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.family-species-tile{min-height:170px}.family-species-photo,.unknown-box{height:118px}.family-row{padding:13px 2px}.family-en{font-size:15px}}
`;document.head.appendChild(s)}

function parseIocFamilies(text){const out=[];for(const raw of text.split(/\r?\n/)){let line=raw.trim();if(!line||!line.includes("|"))continue;line=line.replace(/^[-| :]+|[-| :]+$/g,"");const p=line.split("|").map(x=>x.trim());if(p.length<2)continue;let en=p[0].replace(/^\*+|\*+$/g,"").trim();let la=p[1].replace(/\[([^\]]+)\]\([^\)]+\)/g,"$1").replace(/[*_`]/g,"").trim();if(!/idae$/i.test(la))continue;if(!out.some(x=>x.latin===la))out.push({english:en,latin:la})}return out}
async function loadFamilies(){const cached=readJSON(FAMILY_CACHE,[]);if(cached.length>200){families=cached;return families}try{const r=await fetch(IOC_PROXY,{cache:"no-store"});if(!r.ok)throw 0;const f=parseIocFamilies(await r.text());if(f.length<200)throw 0;families=f;writeJSON(FAMILY_CACHE,f);return f}catch{return loadFamiliesFromINat()}}
async function loadFamiliesFromINat(){const all=[];for(let page=1;page<=3;page++){const r=await fetch(`https://api.inaturalist.org/v1/taxa?taxon_id=3&rank=family&is_active=true&per_page=200&page=${page}`);if(!r.ok)break;const j=await r.json();for(const x of j.results||[])if(!all.some(y=>y.latin===x.name))all.push({english:x.preferred_common_name||x.name,latin:x.name});if((j.results||[]).length<200)break}families=all.sort((a,b)=>a.english.localeCompare(b.english));return families}
async function resolveBirdFamily(b){const key=norm(b.scientificName||b.commonName);if(!key)return null;if(familyMapCache[key])return familyMapCache[key];try{const q=encodeURIComponent(b.scientificName||b.commonName),j=await(await fetch(`https://api.inaturalist.org/v1/taxa?q=${q}&rank=species&per_page=5`)).json();const exact=(j.results||[]).find(x=>norm(x.name)===norm(b.scientificName)||norm(x.preferred_common_name)===norm(b.commonName))||j.results?.[0];if(!exact)return null;let ancestors=exact.ancestors||[];if(!ancestors.length)ancestors=(await(await fetch(`https://api.inaturalist.org/v1/taxa/${exact.id}`)).json()).results?.[0]?.ancestors||[];const fam=ancestors.find(x=>x.rank==="family");if(fam?.name){familyMapCache[key]=fam.name;writeJSON(BIRD_FAMILY_CACHE,familyMapCache);return fam.name}}catch{}return null}
async function refreshOwnedFamilyMap(){familyMapCache=readJSON(BIRD_FAMILY_CACHE,{});owned=await getBirds();const unresolved=owned.filter(b=>!familyMapCache[norm(b.scientificName||b.commonName)]);let i=0;await Promise.all(Array.from({length:Math.min(4,unresolved.length)},async()=>{while(i<unresolved.length)await resolveBirdFamily(unresolved[i++])}))}
function familyOwnedBirds(latin){return owned.filter(b=>familyMapCache[norm(b.scientificName||b.commonName)]===latin)}
async function fetchSpecies(fam){const ck=SPECIES_CACHE_PREFIX+fam.latin,cached=readJSON(ck,null);if(cached?.saved&&Date.now()-cached.saved<2592000000&&cached.items?.length)return cached.items;let familyTaxon=null;try{const j=await(await fetch(`https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(fam.latin)}&rank=family&per_page=5`)).json();familyTaxon=(j.results||[]).find(x=>x.name===fam.latin)||j.results?.[0]}catch{}if(!familyTaxon)return [];const items=[];for(let page=1;page<=20;page++){let rs=[];try{rs=(await(await fetch(`https://api.inaturalist.org/v1/taxa?taxon_id=${familyTaxon.id}&rank=species&is_active=true&per_page=200&page=${page}&order_by=name&order=asc`)).json()).results||[]}catch{break}for(const x of rs)if(x.rank==="species")items.push({common:x.preferred_common_name||x.name,scientific:x.name,id:x.id,observations:x.observations_count||0});if(rs.length<200)break}if(items.length<2){try{for(let page=1;page<=20;page++){const rs=(await(await fetch(`https://api.inaturalist.org/v1/observations/species_counts?taxon_id=${familyTaxon.id}&per_page=200&page=${page}`)).json()).results||[];for(const row of rs){const x=row.taxon;if(x?.rank==="species"&&!items.some(y=>y.scientific===x.name))items.push({common:x.preferred_common_name||x.name,scientific:x.name,id:x.id,observations:row.count||x.observations_count||0})}if(rs.length<200)break}}catch{}}items.sort((a,b)=>a.common.localeCompare(b.common));writeJSON(ck,{saved:Date.now(),items});return items}
function mainPartsHidden(hide){for(const sel of [".toolbar","#rarityFilters","#birdGrid","#emptyState","#mobileAddDock"]){const el=document.querySelector(sel);if(el)el.style.display=hide?"none":""}const add=document.getElementById("addBirdBtn");if(add)add.style.display=hide?"none":""}
function showCompendium(){mainPartsHidden(false);familiesView.style.display="none";document.querySelector('[data-comp-tab="compendium"]')?.classList.add("active");document.querySelector('[data-comp-tab="families"]')?.classList.remove("active");summaryText.style.display=""}
async function showFamilies(){mainPartsHidden(true);familiesView.style.display="block";document.querySelector('[data-comp-tab="families"]')?.classList.add("active");document.querySelector('[data-comp-tab="compendium"]')?.classList.remove("active");summaryText.style.display="none";await renderFamilyIndex()}
async function renderFamilyIndex(){familiesView.innerHTML=`<div class="families-head"><div><h2>Families</h2><p class="muted">IOC World Bird List family index</p></div><div class="families-controls"><input id="familySearch" class="family-search" type="search" placeholder="Search families…" autocomplete="off"><select id="familySort"><option value="alpha">Alphabetical</option><option value="owned">Acquired families first</option></select></div></div><div id="familyStatus" class="family-status">Loading family index…</div><div id="familyList" class="family-list"></div><div class="families-source">Family index: IOC World Bird List v15.2. Suggested rarity for unacquired species uses worldwide iNaturalist observation volume as a general rarity proxy.</div>`;const sort=familySort,search=familySearch;sort.value=sessionStorage.getItem("compFamilySort")||"alpha";search.value=sessionStorage.getItem("compFamilySearch")||"";sort.onchange=()=>{sessionStorage.setItem("compFamilySort",sort.value);drawFamilyRows()};search.oninput=()=>{sessionStorage.setItem("compFamilySearch",search.value);drawFamilyRows()};await loadFamilies();drawFamilyRows();refreshOwnedFamilyMap().then(drawFamilyRows)}
function drawFamilyRows(){const list=document.getElementById("familyList"),sort=document.getElementById("familySort"),search=document.getElementById("familySearch"),status=document.getElementById("familyStatus");if(!list)return;const q=norm(search?.value),rows=families.map(f=>({...f,count:familyOwnedBirds(f.latin).length})).filter(f=>!q||norm(f.english).includes(q)||norm(f.latin).includes(q));rows.sort((a,b)=>sort?.value==="owned"?(b.count-a.count||a.english.localeCompare(b.english)):a.english.localeCompare(b.english));if(status)status.textContent=q?`${rows.length} of ${families.length} families`:`${families.length} families`;list.innerHTML="";if(!rows.length){list.innerHTML='<div class="family-empty-search">No matching families.</div>';return}for(const f of rows){const row=document.createElement("div");row.className="family-row";row.tabIndex=0;row.innerHTML=`<div class="family-row-main"><div class="family-en">${esc(f.english)}</div><div class="family-la">${esc(f.latin)}</div></div><div style="display:flex;align-items:center;gap:9px"><span class="family-progress ${f.count?"has":""}">${f.count?`${f.count} acquired`:""}</span><span class="family-chevron">›</span></div>`;row.onclick=()=>openFamily(f);row.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openFamily(f)}};list.appendChild(row)}}
async function openFamily(fam){familiesView.innerHTML=`<div class="family-detail-head"><button class="family-back" id="familyBack">‹</button><div class="family-detail-title"><h2>${esc(fam.english)}</h2><p>${esc(fam.latin)}</p></div></div><div class="families-head"><div><p class="muted" id="familyCompletion">Loading…</p></div><div class="families-controls"><select id="speciesSort"><option value="alpha">Alphabetical</option><option value="owned">Acquired first</option><option value="rarity-desc">Rarity: rarest first</option><option value="rarity-asc">Rarity: common first</option></select></div></div><div id="familySpeciesStatus" class="family-status">Loading species…</div><div id="familyGrid" class="family-grid"></div>`;familyBack.onclick=renderFamilyIndex;speciesSort.value=sessionStorage.getItem("compSpeciesSort")||"owned";speciesSort.onchange=()=>{sessionStorage.setItem("compSpeciesSort",speciesSort.value);drawSpecies(fam,window.__familySpecies||[])};await refreshOwnedFamilyMap();window.__familySpecies=await fetchSpecies(fam);drawSpecies(fam,window.__familySpecies)}
function findOwnedSpecies(sp){return owned.find(b=>(b.scientificName&&norm(b.scientificName)===norm(sp.scientific))||norm(b.commonName)===norm(sp.common))}
function drawSpecies(fam,species){const grid=familyGrid,status=familySpeciesStatus,completion=familyCompletion,sort=speciesSort;if(!grid)return;const items=species.map(sp=>({sp,bird:findOwnedSpecies(sp)}));for(const b of familyOwnedBirds(fam.latin).filter(b=>!items.some(x=>x.bird?.id===b.id)))items.push({sp:{common:b.commonName,scientific:b.scientificName||"",observations:0},bird:b});const mode=sort?.value||"owned";items.sort((a,b)=>mode==="owned"?(Boolean(b.bird)-Boolean(a.bird)||a.sp.common.localeCompare(b.sp.common)):mode==="rarity-desc"?(RARITY[rarityFor(b)].rank-RARITY[rarityFor(a)].rank||a.sp.common.localeCompare(b.sp.common)):mode==="rarity-asc"?(RARITY[rarityFor(a)].rank-RARITY[rarityFor(b)].rank||a.sp.common.localeCompare(b.sp.common)):a.sp.common.localeCompare(b.sp.common));const acquired=items.filter(x=>x.bird).length;completion.textContent=`${acquired} of ${species.length||items.length} species acquired`;status.textContent=species.length?`${species.length} species listed`:`Couldn’t load the online species list. Your acquired birds in this family are still shown.`;grid.innerHTML="";for(const x of items){const rarityKey=rarityFor(x),r=RARITY[rarityKey],t=document.createElement("button");t.type="button";t.className="family-species-tile "+(x.bird?"owned":"unknown");if(x.bird){const b=x.bird,latest=(b.sightings||[]).slice().sort((a,c)=>(c.date||"").localeCompare(a.date||""))[0];t.innerHTML=`<img class="family-species-photo" alt="" src="${b.coverPhoto?blobUrl(b.coverPhoto):"icon-512.png"}"><span class="family-owned-badge">ACQUIRED</span><div class="family-species-info"><div class="family-species-name">${esc(b.commonName)}</div><div class="family-species-scientific">${esc(b.scientificName||x.sp.scientific)}</div><div class="family-species-meta">${esc([b.country,latest?.location,latest?.date].filter(Boolean).join(" • "))}</div><div class="family-rarity"><span class="family-rarity-dot" style="background:${r.color}"></span>${esc(r.label)}</div></div>`;t.onclick=()=>window.openDetail?.(b.id)}else{t.innerHTML=`<div class="unknown-box">?</div><div class="family-species-info"><div class="family-species-name">${esc(x.sp.common)}</div><div class="family-species-scientific">${esc(x.sp.scientific)}</div><div class="family-rarity suggested"><span class="family-rarity-dot" style="background:${r.color}"></span>Suggested ${esc(r.label)}</div></div>`}grid.appendChild(t)}}
function init(){injectStyles();const app=document.getElementById("app"),top=document.querySelector(".topbar");if(!app||!top)return;const nav=document.createElement("nav");nav.className="comp-nav";nav.innerHTML='<button class="comp-nav-btn active" data-comp-tab="compendium">Compendium</button><button class="comp-nav-btn" data-comp-tab="families">Families</button>';const anchor=document.getElementById("mobileAddDock")||top;anchor.insertAdjacentElement("afterend",nav);const view=document.createElement("section");view.id="familiesView";app.appendChild(view);window.familiesView=view;nav.querySelector('[data-comp-tab="compendium"]').onclick=showCompendium;nav.querySelector('[data-comp-tab="families"]').onclick=showFamilies;familyMapCache=readJSON(BIRD_FAMILY_CACHE,{})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(init,0));else setTimeout(init,0);
})();