(()=>{
const AUSTRALIA_QUERY="Australia";
const norm=s=>String(s||"").trim().toLowerCase();
let modal=null,placeCache=null;
function ensureModal(){if(modal)return modal;const style=document.createElement("style");style.textContent=`.mystery-region-modal{position:fixed;inset:0;z-index:10050;background:rgba(0,0,0,.72);display:none;align-items:flex-end;justify-content:center}.mystery-region-modal.open{display:flex}.mystery-region-sheet{width:min(620px,100%);max-height:82vh;overflow:auto;background:var(--panel,#171a1d);color:var(--text,#fff);border-radius:24px 24px 0 0;padding:18px;padding-bottom:max(24px,env(safe-area-inset-bottom));border:1px solid var(--line,#2d3338)}.mystery-region-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.mystery-region-head h2{margin:0;font-size:22px}.mystery-region-close{border:1px solid var(--line,#2d3338);background:var(--panel2,#202428);color:var(--text,#fff);border-radius:12px;padding:8px 11px}.mystery-region-sub{color:var(--muted,#9aa1a8);font-size:13px;margin:6px 0 15px}.mystery-region-list{display:grid;gap:9px}.mystery-region-item{border:1px solid var(--line,#2d3338);background:var(--panel2,#202428);border-radius:14px;padding:12px 13px}.mystery-region-item strong{display:block}.mystery-region-item span{display:block;color:var(--muted,#9aa1a8);font-size:12px;margin-top:3px}.mystery-region-item.map-link{display:block;color:var(--text,#fff);text-decoration:none;cursor:pointer;transition:transform .12s ease,border-color .12s ease}.mystery-region-item.map-link:active{transform:scale(.985)}.mystery-region-item.map-link:hover{border-color:var(--muted,#9aa1a8)}.mystery-region-map-hint{font-weight:700}.mystery-region-note{color:var(--muted,#9aa1a8);font-size:11px;margin-top:13px}`;document.head.appendChild(style);modal=document.createElement("div");modal.className="mystery-region-modal";modal.innerHTML=`<div class="mystery-region-sheet"><div class="mystery-region-head"><h2 id="mysteryRegionTitle">Where to look</h2><button class="mystery-region-close" type="button">Close</button></div><div id="mysteryRegionSub" class="mystery-region-sub"></div><div id="mysteryRegionList" class="mystery-region-list"></div><div class="mystery-region-note">Suggestions are based on recent iNaturalist research-grade observation place names and are a guide, not a guarantee. Tap a suggested place to open it in Google Maps.</div></div>`;document.body.appendChild(modal);modal.querySelector(".mystery-region-close").onclick=()=>modal.classList.remove("open");modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.remove("open")});return modal}
async function findAustraliaPlace(){if(placeCache)return placeCache;try{const j=await(await fetch(`https://api.inaturalist.org/v1/places/autocomplete?q=${encodeURIComponent(AUSTRALIA_QUERY)}&per_page=10`)).json();placeCache=(j.results||[]).find(x=>norm(x.display_name)==="australia"||norm(x.name)==="australia")||j.results?.[0]||null}catch{}return placeCache}
function cleanPlace(s){return String(s||"").replace(/\s+/g," ").trim()}
function esc(s){return String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}
function rankPlaces(rows,limit=5){const counts=new Map();for(const r of rows||[]){const p=cleanPlace(r.place_guess);if(!p)continue;counts.set(p,(counts.get(p)||0)+1)}return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([name,count])=>({name,count}))}
async function fetchObs(taxonId,extra=""){const u=`https://api.inaturalist.org/v1/observations?taxon_id=${encodeURIComponent(taxonId)}&quality_grade=research&geo=true&per_page=200&order_by=votes&order=desc${extra}`;try{const r=await fetch(u);if(!r.ok)return [];return (await r.json()).results||[]}catch{return []}}
function googleMapsUrl(place){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`}
async function showSuggestions(tile){const title=tile.querySelector(".family-species-name")?.textContent?.trim()||"Species",scientific=tile.querySelector(".family-species-scientific")?.textContent?.trim()||"";let taxonId=tile.dataset.taxonId||"";ensureModal();mysteryRegionTitle.textContent=title;mysteryRegionSub.textContent=scientific?`${scientific} — finding likely regions…`:"Finding likely regions…";mysteryRegionList.innerHTML='<div class="mystery-region-item"><strong>Searching…</strong><span>Checking Australia first, then worldwide records.</span></div>';modal.classList.add("open");if(!taxonId){try{const j=await(await fetch(`https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(scientific||title)}&rank=species&per_page=5`)).json();const x=(j.results||[]).find(v=>norm(v.name)===norm(scientific)||norm(v.preferred_common_name)===norm(title))||j.results?.[0];taxonId=x?.id||""}catch{}}
if(!taxonId){mysteryRegionSub.textContent=scientific;mysteryRegionList.innerHTML='<div class="mystery-region-item"><strong>No range suggestions available</strong><span>I couldn’t match this species to the observation database.</span></div>';return}
const aus=await findAustraliaPlace();let ausRows=[];if(aus?.id)ausRows=await fetchObs(taxonId,`&place_id=${aus.id}`);const globalRows=await fetchObs(taxonId);const ausPlaces=rankPlaces(ausRows,4),globalPlaces=rankPlaces(globalRows,6);const seen=new Set(),items=[];for(const p of ausPlaces){const k=norm(p.name);if(seen.has(k))continue;seen.add(k);items.push({name:p.name,count:p.count,australia:true})}for(const p of globalPlaces){const k=norm(p.name);if(seen.has(k))continue;seen.add(k);items.push({name:p.name,count:p.count,australia:false});if(items.length>=7)break}
if(!items.length){mysteryRegionSub.textContent=scientific;mysteryRegionList.innerHTML='<div class="mystery-region-item"><strong>No recent region data found</strong><span>This species may be poorly represented in iNaturalist records.</span></div>';return}
mysteryRegionSub.textContent=scientific+(ausPlaces.length?" — Australian records prioritised":" — no Australian hotspots found in the sampled records");mysteryRegionList.innerHTML=items.map(x=>`<a class="mystery-region-item map-link" href="${googleMapsUrl(x.name)}" target="_blank" rel="noopener noreferrer"><strong>${x.australia?"🇦🇺 ":""}${esc(x.name)}</strong><span>${x.australia?"Australia priority • ":""}${x.count} sampled observation${x.count===1?"":"s"} • <span class="mystery-region-map-hint">Open in Google Maps ↗</span></span></a>`).join("")}
function install(){const view=document.getElementById("familiesView");if(!view)return;view.addEventListener("click",e=>{const tile=e.target.closest(".family-species-tile.unknown");if(!tile)return;e.preventDefault();e.stopPropagation();showSuggestions(tile)})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(install,0));else setTimeout(install,0);
})();