(()=>{
const POINTS={common:1,uncommon:5,epic:20,mythical:50,legendary:150};
let db=null;
function injectStyles(){if(document.getElementById('pointsCounterStyles'))return;const s=document.createElement('style');s.id='pointsCounterStyles';s.textContent=`.points-counter{display:inline-flex;align-items:center;gap:7px;margin-top:6px;padding:6px 10px;border:1px solid var(--line);background:var(--panel);border-radius:999px;font-size:13px;font-weight:800;color:var(--text);width:max-content;cursor:pointer;user-select:none;transition:transform .12s ease,border-color .12s ease}.points-counter:hover{border-color:var(--muted)}.points-counter:active{transform:scale(.97)}.points-counter .points-star{font-size:14px;line-height:1}.points-counter .points-value{font-variant-numeric:tabular-nums}`;document.head.appendChild(s)}
function ensureCounter(){let el=document.getElementById('pointsCounter');if(el)return el;const summary=document.getElementById('summaryText');if(!summary)return null;el=document.createElement('button');el.type='button';el.id='pointsCounter';el.className='points-counter';el.setAttribute('aria-label','Open achievements');el.innerHTML='<span class="points-star">★</span><span class="points-value">0 pts</span>';el.onclick=()=>window.dispatchEvent(new CustomEvent('open-achievements'));summary.insertAdjacentElement('afterend',el);return el}
async function openDB(){if(db)return db;db=await new Promise((res,rej)=>{const r=indexedDB.open('birdCompendiumDB',1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return db}
async function readBirds(){const d=await openDB();return await new Promise((res,rej)=>{const r=d.transaction('birds').objectStore('birds').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function update(){const el=ensureCounter();if(!el)return;try{const birds=await readBirds();const total=birds.reduce((sum,b)=>sum+(POINTS[String(b.rarity||'common').toLowerCase()]||0),0);el.querySelector('.points-value').textContent=`${total.toLocaleString()} ${total===1?'pt':'pts'}`;el.title='Open Achievements • Common 1 • Uncommon 5 • Epic 20 • Mythical 50 • Legendary 150'}catch{}}
function init(){injectStyles();ensureCounter();update();window.addEventListener('bird-local-change',()=>setTimeout(update,120));window.addEventListener('focus',update);document.addEventListener('visibilitychange',()=>{if(!document.hidden)update()});setInterval(update,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();