(()=>{
const THEME_KEY='birdCompendiumTheme',FONT_KEY='birdCompendiumFont',STATE='compendiumAbilityStatesV1',UNLOCK='compendiumUnlockedAbilitiesV1';
function unlocked(){try{return JSON.parse(localStorage.getItem(UNLOCK)||'[]')}catch{return[]}}
function availableThemes(){const u=unlocked(),x=[['dark','Dark']];if(u.includes('theme-light'))x.push(['light','Light']);if(u.includes('theme-field'))x.push(['parchment','Parchment'],['khaki','Khaki']);if(u.includes('theme-midnight'))x.push(['midnight','Midnight']);if(u.includes('theme-forest'))x.push(['forest','Forest']);return x}
function availableFonts(){const u=unlocked(),x=[['system','System']];if(u.includes('font-garamond'))x.push(['garamond','Garamond']);if(u.includes('font-local'))x.push(['georgia','Georgia'],['typewriter','Typewriter']);if(u.includes('font-rounded'))x.push(['rounded','Rounded']);if(u.includes('font-condensed'))x.push(['condensed','Condensed']);return x}
function applyTheme(theme,persist=true){const items=availableThemes(),allowed=items.some(([id])=>id===theme),valid=allowed?theme:'dark';document.documentElement.dataset.theme=valid;if(persist&&allowed)localStorage.setItem(THEME_KEY,valid);const meta=document.querySelector('meta[name="theme-color"]'),colors={dark:'#101214',light:'#f4f1ea',forest:'#0d1813',parchment:'#e8dcc3',khaki:'#8f875f',midnight:'#090f1a'};if(meta)meta.content=colors[valid]||colors.dark;const p=document.getElementById('themePicker');if(p)p.value=valid}
function applyFont(font,persist=true){const items=availableFonts(),allowed=items.some(([id])=>id===font),valid=allowed?font:'system';document.documentElement.dataset.font=valid;if(persist&&allowed)localStorage.setItem(FONT_KEY,valid);const p=document.getElementById('fontPicker');if(p)p.value=valid}
function makePicker(id,label,items,value,onchange){const p=document.createElement('select');p.id=id;p.className='preference-picker';p.setAttribute('aria-label',label);p.innerHTML=items.map(([k,n])=>`<option value="${k}">${n}</option>`).join('');p.value=value;p.onchange=()=>onchange(p.value);return p}
function setupMobileAdd(topbar,actions,add){add.innerHTML='<span class="add-plus">＋</span><span class="add-label">Add species</span>';let dock=document.getElementById('mobileAddDock');if(!dock){dock=document.createElement('div');dock.id='mobileAddDock';dock.className='mobile-add-dock';topbar.insertAdjacentElement('afterend',dock)}let observer=null;const place=()=>{const mobile=matchMedia('(max-width:700px)').matches;if(observer){observer.disconnect();observer=null}add.classList.remove('mobile-floating','mobile-docked');if(mobile){if(add.parentElement!==dock)dock.appendChild(add);add.classList.add('mobile-docked');observer=new IntersectionObserver(es=>add.classList.toggle('mobile-floating',!es[0]?.isIntersecting),{threshold:.15});observer.observe(dock)}else if(add.parentElement!==actions)actions.appendChild(add)};place();addEventListener('resize',place,{passive:true})}
function refreshControls(){const controls=document.querySelector('.preference-controls');if(!controls)return;controls.innerHTML='';const u=unlocked();if(u.some(x=>x.startsWith('theme-'))){const t=availableThemes(),saved=localStorage.getItem(THEME_KEY)||'dark',v=t.some(x=>x[0]===saved)?saved:'dark';controls.append(makePicker('themePicker','App theme',t,v,v=>applyTheme(v,true)))}else applyTheme('dark',false);if(u.some(x=>x.startsWith('font-'))){const f=availableFonts(),saved=localStorage.getItem(FONT_KEY)||'system',v=f.some(x=>x[0]===saved)?saved:'system';controls.append(makePicker('fontPicker','App font',f,v,v=>applyFont(v,true)))}else applyFont('system',false);controls.classList.toggle('has-preferences',controls.children.length>0)}
function restorePreferences(){applyTheme(localStorage.getItem(THEME_KEY)||'dark',false);applyFont(localStorage.getItem(FONT_KEY)||'system',false)}
async function reconcileCoreUnlocks(){try{const db=await new Promise((res,rej)=>{const r=indexedDB.open('birdCompendiumDB',1);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),birds=await new Promise((res,rej)=>{const r=db.transaction('birds').objectStore('birds').getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});const pt={common:1,uncommon:5,epic:20,mythical:50,legendary:150},rarity={common:0,uncommon:0,epic:0,mythical:0,legendary:0},locations=new Set(),countries=new Set();let points=0,notes=0,multi=0;for(const b of birds){const k=String(b.rarity||'').toLowerCase();rarity[k]=(rarity[k]||0)+1;points+=pt[k]||0;if(String(b.notes||'').trim())notes++;if((b.sightings||[]).length>=2)multi++;if(b.country)countries.add(String(b.country).trim().toLowerCase());for(const s of b.sightings||[])if(s.location)locations.add(String(s.location).trim().toLowerCase())}let state={};try{state=JSON.parse(localStorage.getItem(STATE)||'{}')}catch{}const earn=id=>{if(!state[id])state[id]={unlocked:true,enabled:false};else state[id].unlocked=true};if(birds.length>=1)earn('feather-logo');if(points>=5)earn('theme-light');if(rarity.uncommon>=1)earn('font-garamond');if(['common','uncommon','epic','mythical','legendary'].every(k=>rarity[k]>0))earn('spectrum');if(countries.size>=3)earn('maltese');if(notes>=5)earn('theme-field');if(multi>=3)earn('eyes');if(locations.size>=5)earn('font-local');localStorage.setItem(STATE,JSON.stringify(state));localStorage.setItem(UNLOCK,JSON.stringify(Object.entries(state).filter(([,v])=>v?.unlocked).map(([k])=>k)));refreshControls();restorePreferences();window.dispatchEvent(new Event('achievement-abilities-changed'))}catch(e){console.warn('Could not reconcile achievement preferences',e)}}
function init(){document.documentElement.dataset.theme='dark';document.documentElement.dataset.font='system';const topbar=document.querySelector('.topbar'),add=document.getElementById('addBirdBtn');if(!topbar||!add)return;let actions=topbar.querySelector('.topbar-actions');if(!actions){actions=document.createElement('div');actions.className='topbar-actions';topbar.appendChild(actions);actions.appendChild(add)}let controls=actions.querySelector('.preference-controls');if(!controls){controls=document.createElement('div');controls.className='preference-controls';actions.insertBefore(controls,add)}restorePreferences();refreshControls();setupMobileAdd(topbar,actions,add);reconcileCoreUnlocks();addEventListener('achievement-abilities-changed',()=>{refreshControls();restorePreferences()});addEventListener('bird-local-change',()=>setTimeout(reconcileCoreUnlocks,150));addEventListener('focus',reconcileCoreUnlocks);document.addEventListener('visibilitychange',()=>{if(!document.hidden)reconcileCoreUnlocks()});setTimeout(reconcileCoreUnlocks,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();